# PREPARING DATA

#### We are going to see the data of the different files and prepare them to be able to work with them, since as we have seen in the previous step, each one of them has different characteristics.

## Importing libraries

In [1]:
import pandas as pd
import numpy as np

## Collecting and visualizing data

### Working with data from 2014

In [2]:
# Saving data in a dataframe

data_meteo_14 = pd.read_csv('dataset/meteo/sunlab-faro-meteo-2014.csv',sep=';')
data_pv_14 = pd.read_csv('dataset/pv/sunlab-faro-pv-2014.csv',sep=';')

In [3]:
# Seeing shape

data_meteo_14.shape

(524863, 9)

In [4]:
data_pv_14.shape

(262145, 25)

In [5]:
# Seeing a example

data_meteo_14.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Diffuse Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2014-02-28T04:59:00+00:00,13.783334,1.417539,1.672896,0.504882,2.116667,252.16572,NaN,NaN
1,2014-11-07T06:46:00+00:00,24.800002,193.118980,43.530248,10.453270,0.400000,159.51002,NaN,NaN
2,2014-11-07T06:54:00+00:00,25.249998,226.530840,46.454708,11.877266,0.600000,110.83258,NaN,NaN
3,2014-02-28T05:04:00+00:00,13.700000,1.183479,1.657202,0.505982,1.150000,211.66448,NaN,NaN
4,2014-11-07T07:03:00+00:00,24.699998,261.758280,49.932436,13.540898,0.466667,107.76016,NaN,NaN

In [6]:
data_pv_14.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2014-11-15T13:21:00+00:00,28.7,6.0100,172.48700,27.85,7.0300,195.785500,29.00,4.4125,127.962500,...,178.211625,27.50,7.0425,193.66875,28.45,4.3750,124.468750,36.4,36.4,29.5
1,2014-11-15T13:23:00+00:00,28.4,6.0375,171.46500,27.85,7.0200,195.507000,29.00,4.3925,127.382500,...,179.733000,27.30,7.0725,193.07925,28.35,4.3675,123.818625,36.7,36.9,29.6
2,2014-11-15T13:26:00+00:00,28.7,5.9975,172.12825,28.05,6.9925,196.139625,28.85,4.4025,127.012125,...,179.918125,27.60,7.0150,193.61400,28.35,4.3575,123.535125,35.3,36.0,28.7
3,2014-11-15T13:29:00+00:00,28.8,5.9300,170.78400,28.15,6.9300,195.079500,29.15,4.3175,125.855125,...,178.730625,27.60,6.9525,191.88900,28.45,4.2975,122.263875,34.5,35.0,28.1
4,2014-11-15T13:32:00+00:00,28.8,5.8050,167.18400,28.95,6.5525,189.694875,29.15,4.2200,123.013000,...,174.942500,27.75,6.7650,187.72875,28.35,4.2125,119.424375,34.3,34.7,28.0

In [7]:
# Looking columns

data_pv_14.columns

Index(['Datetime', 'A_Vertical - Voltage DC [V]',
       'A_Vertical - Current DC [A]', 'A_Vertical - Power DC [W]',
       'A_Optimal - Voltage DC [V]', 'A_Optimal - Current DC [A]',
       'A_Optimal - Power DC [W]', 'A_Horizontal - Voltage DC [V]',
       'A_Horizontal - Current DC [A]', 'A_Horizontal - Power DC [W]',
       'A_Vertical - Temperature [ºC]', 'A_Optimal - Temperature [ºC]',
       'A_Horizontal - Temperature [ºC]', 'B_Vertical - Voltage DC [V]',
       'B_Vertical - Current DC [A]', 'B_Vertical - Power DC [W]',
       'B_Optimal - Voltage DC [V]', 'B_Optimal - Current DC [A]',
       'B_Optimal - Power DC [W]', 'B_Horizontal - Voltage DC [V]',
       'B_Horizontal - Current DC [A]', 'B_Horizontal - Power DC [W]',
       'B_Vertical - Temperature [ºC]', 'B_Optimal - Temperature [ºC]',
       'B_Horizontal - Temperature [ºC]'],
      dtype='object')

In [8]:
# Renaming columns

data_meteo_14 = data_meteo_14.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [9]:
data_pv_14 = data_pv_14.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [10]:
# Checking renamed

data_meteo_14.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure
0,2014-02-28T04:59:00+00:00,13.783334,1.417539,1.672896,0.504882,2.116667,252.16572,NaN,NaN
1,2014-11-07T06:46:00+00:00,24.800002,193.118980,43.530248,10.453270,0.400000,159.51002,NaN,NaN
2,2014-11-07T06:54:00+00:00,25.249998,226.530840,46.454708,11.877266,0.600000,110.83258,NaN,NaN
3,2014-02-28T05:04:00+00:00,13.700000,1.183479,1.657202,0.505982,1.150000,211.66448,NaN,NaN
4,2014-11-07T07:03:00+00:00,24.699998,261.758280,49.932436,13.540898,0.466667,107.76016,NaN,NaN

In [11]:
data_pv_14.head()

,Datetime,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,A_Optimal_CDC,A_Optimal_PDC,A_Horizontal_VDC,A_Horizontal_CDC,A_Horizontal_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2014-11-15T13:21:00+00:00,28.7,6.0100,172.48700,27.85,7.0300,195.785500,29.00,4.4125,127.962500,...,178.211625,27.50,7.0425,193.66875,28.45,4.3750,124.468750,36.4,36.4,29.5
1,2014-11-15T13:23:00+00:00,28.4,6.0375,171.46500,27.85,7.0200,195.507000,29.00,4.3925,127.382500,...,179.733000,27.30,7.0725,193.07925,28.35,4.3675,123.818625,36.7,36.9,29.6
2,2014-11-15T13:26:00+00:00,28.7,5.9975,172.12825,28.05,6.9925,196.139625,28.85,4.4025,127.012125,...,179.918125,27.60,7.0150,193.61400,28.35,4.3575,123.535125,35.3,36.0,28.7
3,2014-11-15T13:29:00+00:00,28.8,5.9300,170.78400,28.15,6.9300,195.079500,29.15,4.3175,125.855125,...,178.730625,27.60,6.9525,191.88900,28.45,4.2975,122.263875,34.5,35.0,28.1
4,2014-11-15T13:32:00+00:00,28.8,5.8050,167.18400,28.95,6.5525,189.694875,29.15,4.2200,123.013000,...,174.942500,27.75,6.7650,187.72875,28.35,4.2125,119.424375,34.3,34.7,28.0

In [12]:
# Changing the time format to UTC

data_meteo_14['Datetime'] = pd.to_datetime(data_meteo_14['Datetime'])
data_pv_14['Datetime'] = pd.to_datetime(data_pv_14['Datetime'])

In [13]:
# Sortting by date

data_meteo_14 = data_meteo_14.sort_values('Datetime').reset_index(drop=True)
data_pv_14 = data_pv_14.sort_values('Datetime').reset_index(drop=True)

In [14]:
# Joining both tables by date

final_dataset_14 = pd.merge (left = data_meteo_14, right = data_pv_14, left_on = 'Datetime', right_on = 'Datetime')

In [15]:
# Seeing the shape

final_dataset_14.shape

(262131, 33)

In [16]:
# Resetting indexes

final_dataset_14.reset_index()

,index,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,0,2014-01-01 07:41:00,9.700000,7.131149,6.929149,0.751824,0.700000,275.33384,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2,9.7,8.8
1,1,2014-01-01 07:42:00,9.700000,7.040442,6.847878,0.781930,0.666667,278.50306,NaN,NaN,...,NaN,18.30,0.130512,2.388366,NaN,NaN,NaN,10.2,9.7,8.8
2,2,2014-01-01 07:43:00,9.700000,6.594407,6.672844,0.813929,0.616667,284.66712,NaN,NaN,...,NaN,22.35,0.052500,1.173375,NaN,NaN,NaN,10.2,9.7,8.8
3,3,2014-01-01 07:44:00,9.700000,7.358729,6.752742,0.849919,0.666667,278.66666,NaN,NaN,...,0.900375,24.35,0.052500,1.278375,NaN,NaN,NaN,10.3,9.7,8.8
4,4,2014-01-01 07:45:00,9.700000,7.470711,7.181158,0.886891,0.633333,272.66636,NaN,NaN,...,0.992250,25.25,0.052500,1.325625,NaN,NaN,NaN,10.3,9.7,8.9
5,5,2014-01-01 07:46:00,9.700000,7.546620,6.920961,0.926726,0.633333,273.33472,NaN,NaN,...,1.134000,29.80,0.012500,0.372500,NaN,NaN,NaN,10.3,9.8,8.9
6,6,2014-01-01 07:47:00,9.700000,8.045695,7.797984,0.968047,0.583333,281.33312,NaN,NaN,...,1.131000,29.95,0.012500,0.374375,NaN,NaN,NaN,10.3,9.8,8.9
7,7,2014-01-01 07:48:00,9.783334,7.864246,7.420328,1.012543,0.533333,286.16852,NaN,NaN,...,1.228500,30.15,0.010000,0.301500,NaN,NaN,NaN,10.4,9.8,8.8
8,8,2014-01-01 07:49:00,9.800000,8.839786,8.384774,1.059740,0.616667,299.76818,NaN,NaN,...,1.323000,30.35,0.010000,0.303500,19.55,0.0575,1.124125,10.4,9.8,8.8
9,9,2014-01-01 07:50:00,9.800000,9.199440,8.635354,1.108016,0.716667,327.67166,NaN,NaN,...,1.437625,30.50,0.012500,0.381250,18.90,0.0600,1.134000,10.5,9.8,8.8
10,10,2014-01-01 07:51:00,9.800000,9.797992,9.120956,1.160777,0.683333,335.83412,NaN,NaN,...,1.559250,24.60,0.085000,2.091000,21.20,0.0650,1.378000,10.5,9.8,8.8
11,11,2014-01-01 07:52:00,9.800000,10.845956,10.548938,1.214622,0.516667,336.14196,NaN,NaN,...,1.653750,19.45,0.102500,1.993625,19.15,0.0750,1.436250,10.5,9.8,8.9
12,12,2014-01-01 07:53:00,9.800000,11.532682,11.137218,1.270430,0.350000,340.78228,NaN,NaN,...,1.833000,19.55,0.112500,2.199375,19.15,0.0825,1.579875,10.6,9.9,8.9
13,13,2014-01-01 07:54:00,9.800000,12.889596,12.623816,1.329821,0.433333,353.13304,NaN,NaN,...,2.131875,19.45,0.135000,2.625750,19.15,0.0950,1.819250,10.7,9.9,9.0
14,14,2014-01-01 07:55:00,9.800000,15.322952,14.370770,1.392079,0.350000,350.90784,NaN,NaN,...,2.639000,19.50,0.187500,3.656250,18.60,0.1075,1.999500,10.7,9.9,9.0
15,15,2014-01-01 07:56:00,9.750002,17.806176,15.842494,1.456903,0.450000,330.16620,NaN,NaN,...,3.168750,19.35,0.302500,5.853375,19.15,0.1250,2.393750,10.8,10.0,9.1
16,16,2014-01-01 07:57:00,9.700000,20.496008,16.637502,1.524187,0.416667,323.00052,NaN,NaN,...,3.402000,19.30,0.405000,7.816500,19.20,0.1400,2.688000,10.8,10.0,9.1
17,17,2014-01-01 07:58:00,9.700000,23.379710,18.832956,1.594219,0.583333,321.99792,NaN,NaN,...,3.932125,19.40,0.527500,10.233500,19.05,0.1550,2.952750,10.8,10.1,9.1
18,18,2014-01-01 07:59:00,9.700000,26.028964,20.516470,1.665414,0.683333,323.66894,NaN,NaN,...,4.194125,19.35,0.595000,11.513250,19.05,0.1675,3.190875,10.8,10.2,9.1
19,19,2014-01-01 08:00:00,9.600000,28.432374,22.039390,1.748521,0.733333,315.00428,NaN,NaN,...,4.417500,19.55,0.665000,13.000750,19.05,0.1850,3.524250,10.9,10.3,9.1
20,20,2014-01-01 08:01:00,9.600000,31.181946,24.364550,1.822408,0.716667,317.49102,NaN,NaN,...,4.737500,19.50,0.730000,14.235000,19.00,0.2025,3.847500,11.0,10.5,9.1
21,21,2014-01-01 08:02:00,9.583334,33.797328,24.473078,1.898202,0.616667,310.02624,NaN,NaN,...,5.042375,19.65,0.795000,15.621750,19.10,0.2150,4.106500,11.1,10.6,9.2
22,22,2014-01-01 08:03:00,9.500000,36.174944,25.805766,1.974671,0.650000,309.82678,NaN,NaN,...,5.670000,19.85,0.860000,17.071000,19.15,0.2300,4.404500,11.3,10.7,9.2
23,23,2014-01-01 08:04:00,9.500000,38.635740,27.304688,2.052018,0.583333,315.67154,NaN,NaN,...,9.733500,19.60,0.922500,18.081000,19.15,0.2450,4.691750,11.5,10.9,9.3
24,24,2014-01-01 08:05:00,9.500000,40.847224,27.508584,2.128413,0.633333,316.16638,NaN,NaN,...,14.382750,19.65,0.977500,19.207875,18.25,0.2625,4.790625,11.8,11.0,9.3
25,25,2014-01-01 08:06:00,9.500000,42.763676,28.500464,2.205930,0.566667,310.06338,NaN,NaN,...,17.192625,19.65,1.032500,20.288625,19.05,0.2725,5.191125,12.1,11.1,9.4
26,26,2014-01-01 08:07:00,9.500000,44.685288,29.439650,2.282930,0.533333,310.99832,NaN,NaN,...,21.448000,19.60,1.080000,21.168000,18.95,0.2850,5.400750,12.4,11.1,9.4
27,27,2014-01-01 08:08:00,9.500000,45.998580,29.023722,2.359364,0.683333,318.99890,NaN,NaN,...,23.655375,19.65,1.130000,22.204500,18.90,0.2975,5.622750,12.8,11.3,9.4
28,28,2014-01-01 08:09:00,9.500000,49.114324,30.352630,2.437052,0.683333,320.67962,NaN,NaN,...,23.848875,19.65,1.192500,23.432625,18.90,0.3125,5.906250,13.0,11.4,9.5
29,29,2014-01-01 08:10:00,9.433334,50.925736,31.316474,2.514197,0.733333,320.40860,NaN,NaN,...,21.285000,19.65,1.200000,23.580000,18.90,0.3200,6.048000,13.3,11.6,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262101,262101,2014-12-31 17:05:00,13.683334,23.551546,23.394934,2.231155,1.833333,292.31912,NaN,NaN,...,0.222750,26.55,0.100000,2.655000,23.25,0.0975,2.266875,18.2,15.6,13.1
262102,262102,2014-12-31 17:06:00,13.583334,22.815424,22.259454,2.156028,1.633333,299.16868,NaN,NaN,...,0.222375,30.55,0.012500,0.381875,23.25,0.0925,2.150625,17.8,15.3,13.0
262103,262103,2014-12-31 17:07:00,13.500000,22.233398,22.016480,2.075687,1.850000,298.16406,NaN,NaN,...,0.222375,30.50,0.010000,0.305000,30.10,0.0125,0.376250,17.4,14.9,12.8
262104,262104,2014-12-31 17:08:00,13.400002,20.719248,20.533000,1.997073,1.566667,300.65768,NaN,NaN,...,0.221250,24.10,0.102500,2.470250,30.00,0.0125,0.375000,17.0,14.7,12.8
262105,262105,2014-12-31 17:09:00,13.400002,19.625614,18.753036,1.916118,1.433333,297.49572,NaN,NaN,...,1.732500,24.05,0.097500,2.344875,18.45,0.0900,1.660500,16.6,14.4,12.6
262106,262106,2014-12-31 17:10:00,13.300000,18.417768,18.468500,1.837413,1.266667,303.16858,NaN,NaN,...,1.740000,30.25,0.010000,0.302500,19.05,0.0850,1.619250,16.3,14.2,12.5
262107,262107,2014-12-31 17:11:00,13.283334,17.978544,17.220764,1.761439,1.483333,306.83094,NaN,NaN,...,1.627500,30.20,0.012500,0.377500,19.15,0.0800,1.532000,16.0,14.0,12.4
262108,262108,2014-12-31 17:12:00,13.200000,16.747360,16.612000,1.686030,1.450000,304.49896,NaN,NaN,...,1.447500,26.95,0.067500,1.819125,14.60,0.0775,1.131500,15.7,13.7,12.2
262109,262109,2014-12-31 17:13:00,13.200000,16.406482,16.018878,1.620369,1.416667,301.49908,NaN,NaN,...,0.289000,29.95,0.012500,0.374375,29.35,0.0125,0.366875,15.5,13.6,12.1
262110,262110,2014-12-31 17:14:00,13.100000,14.930478,14.737218,1.550297,1.400000,294.16416,NaN,NaN,...,0.215625,29.80,0.012500,0.372500,29.15,0.0125,0.364375,15.2,13.4,12.1
262111,262111,2014-12-31 17:15:00,13.100000,14.780438,14.099778,1.479090,1.300000,290.66620,NaN,NaN,...,1.193750,18.55,0.080000,1.484000,28.95,0.0125,0.361875,15.0,13.3,12.0
262112,262112,2014-12-31 17:16:00,13.000000,13.430290,13.213404,1.420650,1.500000,292.83346,NaN,NaN,...,1.050500,29.50,0.012500,0.368750,28.75,0.0125,0.359375,14.8,13.1,11.9
262113,262113,2014-12-31 17:17:00,13.000000,12.764540,12.239990,1.355901,1.366667,291.83332,NaN,NaN,...,0.955000,29.30,0.010000,0.293000,28.50,0.0150,0.427500,14.6,13.0,11.8
262114,262114,2014-12-31 17:18:00,12.900002,12.325768,11.954498,1.292818,1.183333,290.16540,NaN,NaN,...,0.760000,29.10,0.010000,0.291000,28.25,0.0150,0.423750,14.5,12.9,11.7
262115,262115,2014-12-31 17:19:00,12.900002,11.775570,11.371052,1.240272,1.250000,291.99938,NaN,NaN,...,0.206625,28.85,0.012500,0.360625,27.95,0.0125,0.349375,14.3,12.8,11.6
262116,262116,2014-12-31 17:20:00,12.850000,10.501234,10.527836,1.180723,1.133333,298.83414,NaN,NaN,...,0.204000,28.65,0.012500,0.358125,27.60,0.0150,0.414000,14.1,12.7,11.5
262117,262117,2014-12-31 17:21:00,12.800000,10.668374,10.337658,1.127326,1.150000,305.99894,NaN,NaN,...,0.267500,28.30,0.010000,0.283000,27.20,0.0150,0.408000,14.0,12.6,11.5
262118,262118,2014-12-31 17:22:00,12.800000,9.482820,9.164352,1.073710,1.150000,303.66608,NaN,NaN,...,0.196875,28.00,0.012500,0.350000,NaN,NaN,NaN,13.8,12.5,11.4
262119,262119,2014-12-31 17:23:00,12.800000,8.905614,8.894244,1.023882,1.316667,304.32624,NaN,NaN,...,0.257000,27.65,0.012500,0.345625,26.20,0.0150,0.393000,13.7,12.4,11.3
262120,262120,2014-12-31 17:24:00,12.800000,8.702238,8.376970,0.979641,1.116667,307.33404,NaN,NaN,...,0.186750,27.20,0.012500,0.340000,25.55,0.0150,0.383250,13.6,12.4,11.3
262121,262121,2014-12-31 17:25:00,12.800000,7.726969,7.629651,0.931571,1.366667,303.00778,NaN,NaN,...,0.238500,26.65,0.012500,0.333125,24.60,0.0150,0.369000,13.5,12.4,11.2
262122,262122,2014-12-31 17:26:00,12.700000,7.609007,7.049950,0.892385,1.166667,303.49298,NaN,NaN,...,0.225000,26.00,0.015000,0.390000,23.35,0.0175,0.408625,13.3,12.3,11.2
262123,262123,2014-12-31 17:27:00,12.700000,6.295417,6.028898,0.853501,1.200000,303.33166,NaN,NaN,...,0.201000,25.15,0.012500,0.314375,21.10,0.0175,0.369250,13.2,12.2,11.1
262124,262124,2014-12-31 17:28:00,12.700000,6.525567,6.184345,0.815306,1.033333,302.50100,NaN,NaN,...,NaN,24.10,0.012500,0.301250,NaN,NaN,NaN,13.1,12.0,11.0
262125,262125,2014-12-31 17:29:00,12.650000,6.729122,6.301360,0.788235,1.083333,300.33050,NaN,NaN,...,NaN,22.20,0.012500,0.277500,NaN,NaN,NaN,13.0,11.9,10.9
262126,262126,2014-12-31 17:30:00,12.600000,5.824658,5.729233,0.750715,1.116667,293.99914,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8,11.9,10.8
262127,262127,2014-12-31 17:31:00,12.600000,5.625719,4.953854,0.727033,1.083333,304.33356,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7,11.8,10.7
262128,262128,2014-12-31 17:32:00,12.533334,5.638842,5.304980,0.697024,1.050000,304.33368,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,11.8,10.6
262129,262129,2014-12-31 17:33:00,12.500000,5.373980,5.200505,0.673228,1.116667,308.16662,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,11.7,10.6
262130,262130,2014-12-31 17:34:00,12.500000,4.707419,4.852263,0.651809,1.066667,311.33050,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.5,11.7,10.5

In [17]:
# Dropping Datetime, Precipitation and Atmospheric pressure. They do not provide information.

final_dataset_14.drop(['Datetime', 'Precipitation', 'Atmospheric_pressure'], 
                                         axis='columns', inplace=True)

In [18]:
# Describing data. There are outliers. It is necesary to delete them.

final_dataset_14.columns

Index(['Ambient_Temperature', 'Global_Radiation', 'Diffuse_Radiation',
       'Ultraviolet', 'Wind_Velocity', 'Wind_direction', 'A_Vertical_VDC',
       'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC', 'A_Optimal_CDC',
       'A_Optimal_PDC', 'A_Horizontal_VDC', 'A_Horizontal_CDC',
       'A_Horizontal_PDC', 'A_Vertical_Temperature', 'A_Optimal_Temperature',
       'A_Horizontal_Temperature', 'B_Vertical_VDC', 'B_Vertical_CDC',
       'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC', 'B_Optimal_PDC',
       'B_Horizontal_VDC', 'B_Horizontal_CDC', 'B_Horizontal_PDC',
       'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'],
      dtype='object')

In [19]:
# Procedure to fill gaps using mean between previus and next data.

def fill_gap (dataset, columns_to_fill):
    
    # Fill NaN interpolating between before and after values
        
    dataset = dataset.interpolate(method='linear')
    
    for nam_col in list(columns_to_fill):
        
        # Reference to considere outliers.
        
        ref_low = dataset[nam_col].mean() - dataset[nam_col].std() * 3
        ref_high = dataset[nam_col].mean() + dataset[nam_col].std() * 3
        
        # Saving index of outliers.
        
        indexes = dataset.index[(dataset[nam_col]<ref_low) & (dataset[nam_col]<ref_high)]
        
        # Changing outliers for a regular data. Taking care with extreme indexes.
        for index in indexes:
                
            if 0 < index < len(dataset):
                dataset.loc[index, nam_col] = (np.mean([dataset.loc[index-1, nam_col], 
                                                        dataset.loc[index+1, nam_col]]))   
            elif index == 0:
                dataset.loc[index, nam_col] = dataset.loc[(index+1), nam_col]
                
            elif index == len(dataset):
                dataset.loc[index, nam_col] = dataset.loc[index-1, nam_col]

    # If there are nay NaN, drop row
    
    dataset = dataset.dropna(how='any')
    
    return dataset

In [20]:
# Applying procedure

final_dataset_14 = fill_gap (final_dataset_14, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [21]:
# Describing data

final_dataset_14.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,...,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000
mean,20.023628,438.848087,122.966855,26.953351,2.580107,207.405046,26.410945,2.069233,58.536798,27.557843,...,59.446463,26.456785,3.539500,96.971297,26.401863,3.152274,86.694989,28.210375,29.512916,27.728735
std,5.119721,318.224739,102.628337,19.622634,1.306621,85.177784,4.116195,1.728860,51.344133,2.095805,...,53.840742,3.422042,2.647375,72.682837,3.681483,2.324980,64.422343,7.422163,9.502396,8.988269
min,4.200001,0.876493,1.591053,0.500673,0.000000,0.000000,11.205263,0.000000,0.000000,11.237787,...,0.000000,11.858594,0.000000,0.000000,13.312500,0.000000,0.000000,4.810156,4.100000,3.100000
25%,16.000000,146.076505,57.101142,9.524865,1.616667,137.509050,26.550000,0.622500,14.210875,26.950000,...,13.515000,26.800000,0.982500,24.276000,26.750000,1.042500,25.032594,22.500000,21.700000,20.600000
50%,20.166666,406.791180,94.517320,23.863689,2.500000,226.826260,28.050000,1.625000,45.135000,27.850000,...,44.444000,27.400000,3.205000,90.747062,27.500000,2.810000,80.063125,28.900000,29.500000,27.500000
75%,23.800002,707.318620,156.228685,42.676916,3.416667,271.970655,29.250000,3.150000,91.253344,28.850000,...,92.767500,28.100000,6.097500,167.408438,28.350000,5.105000,142.698625,33.800000,37.100000,34.900000
max,35.399996,1438.887200,776.552080,81.365264,9.833334,359.998440,36.800000,8.095000,228.279000,36.900000,...,244.876500,36.550000,10.237500,303.030000,36.000000,10.237500,297.399375,55.100000,56.900000,105.800000

### Working with data from 2015

In [22]:
data_meteo_15 = pd.read_csv('dataset/meteo/sunlab-faro-meteo-2015.csv',sep=';')
data_pv_15 = pd.read_csv('dataset/pv/sunlab-faro-pv-2015.csv',sep=';')

In [23]:
data_meteo_15.shape

(437159, 9)

In [24]:
data_pv_15.shape

(242735, 25)

In [25]:
data_meteo_15 = data_meteo_15.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [26]:
data_pv_15 = data_pv_15.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [27]:
data_meteo_15['Datetime'] = pd.to_datetime(data_meteo_15['Datetime'])
data_pv_15['Datetime'] = pd.to_datetime(data_pv_15['Datetime'])

In [28]:
# Sortting by date

data_meteo_15 = data_meteo_15.sort_values('Datetime').reset_index(drop=True)
data_pv_15 = data_pv_15.sort_values('Datetime').reset_index(drop=True)

In [29]:
final_dataset_15 = pd.merge (left = data_meteo_15, right = data_pv_15, left_on = 'Datetime', right_on = 'Datetime')

In [30]:
final_dataset_15.shape

(225510, 33)

In [31]:
final_dataset_15.drop(['Datetime', 'Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [32]:
final_dataset_15 = fill_gap (final_dataset_15, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [33]:
final_dataset_15.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,...,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000
mean,21.135466,462.059383,127.921139,27.785569,2.586359,196.572236,26.066274,2.060262,58.080369,27.322064,...,58.567904,26.166733,3.629897,99.033002,26.247499,3.210207,88.318760,29.068731,30.657794,28.858024
std,5.432284,319.843669,103.215874,19.355916,1.306946,85.386276,4.587664,1.702535,50.826816,2.269292,...,52.986153,3.729086,2.689057,73.652859,4.005837,2.310003,64.180791,7.514115,9.771258,9.185867
min,3.166667,1.337505,1.606723,0.557327,0.000000,0.000000,12.350000,0.000000,0.000000,10.910491,...,0.000000,12.000000,0.000000,0.000000,11.700000,0.000000,0.000000,3.515234,2.300000,1.600000
25%,17.250000,161.759810,60.120680,10.066195,1.616667,125.674250,26.400000,0.637500,13.953750,26.900000,...,13.112000,26.700000,1.005000,24.593125,26.750000,1.067500,25.574813,23.600000,22.800000,21.700000
50%,21.199998,442.888080,99.838872,25.360398,2.516667,215.830100,27.850000,1.630000,44.797500,27.650000,...,43.625000,27.300000,3.340000,94.116750,27.500000,2.967500,84.736750,30.000000,31.000000,29.100000
75%,25.000000,742.343720,159.232030,44.226692,3.416667,261.980850,29.150000,3.105000,90.117000,28.650000,...,90.884625,27.950000,6.290000,171.675000,28.350000,5.202500,146.001250,34.900000,38.700000,36.100000
max,37.166668,1421.328200,720.352560,84.266016,9.700002,359.999160,34.400000,7.997500,236.664000,34.650000,...,243.975000,34.900000,10.237500,302.006250,34.450000,10.237500,300.982500,48.400000,55.500000,53.300000

### Working with data from 2016

In [34]:
data_meteo_16 = pd.read_csv('dataset/meteo/sunlab-faro-meteo-2016.csv',sep=';')
data_pv_16 = pd.read_csv('dataset/pv/sunlab-faro-pv-2016.csv',sep=';')

In [35]:
data_meteo_16.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Direct Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2016-03-22T07:58:00+00:00,11.083334,307.19950,144.84512,12.533846,3.133333,300.66464,NaN,NaN
1,2016-03-22T08:00:00+00:00,11.100000,174.47252,150.80226,10.975560,2.900000,294.33660,NaN,NaN
2,2016-03-22T08:02:00+00:00,11.166666,360.01548,143.93522,14.223366,3.766667,300.83378,NaN,NaN
3,2016-03-22T08:06:00+00:00,11.233334,375.56660,128.84222,15.575274,2.683334,299.33326,NaN,NaN
4,2016-03-22T08:08:00+00:00,11.300000,376.88700,120.42222,15.897234,3.433333,295.83228,NaN,NaN

In [36]:
data_pv_16.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2016-02-11T15:34:00+00:00,28.50,1.1275,32.13375,29.40,1.5725,46.231500,27.10,1.4625,39.63375,...,31.050000,27.55,1.5675,43.184625,27.25,1.4125,38.490625,24.5,22.8,22.5
1,2016-06-10T13:23:00+00:00,29.50,1.7725,52.28875,34.20,0.8050,27.531000,28.50,4.2500,121.12500,...,51.051000,28.15,3.8550,108.518250,28.10,4.1750,117.317500,37.0,42.3,43.5
2,2016-02-11T10:41:00+00:00,30.20,1.4775,44.62050,29.25,2.4250,70.931250,29.25,2.2850,66.83625,...,44.846875,28.70,2.3825,68.377750,28.95,2.2275,64.486125,27.4,25.7,24.9
3,2016-06-10T13:25:00+00:00,29.50,1.9775,58.33625,34.45,0.8100,27.904500,28.30,5.0950,144.18850,...,56.889875,27.70,4.6775,129.566750,28.35,4.9400,140.049000,37.2,43.3,44.4
4,2016-02-11T10:44:00+00:00,29.75,1.4450,42.98875,29.25,2.2375,65.446875,30.15,1.9200,57.88800,...,42.333000,28.30,2.2000,62.260000,28.70,1.9550,56.108500,27.1,25.3,24.6

In [37]:
data_meteo_16.shape

(399744, 9)

In [38]:
data_pv_16.shape

(177772, 25)

In [39]:
data_meteo_16.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Direct Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2016-03-22T07:58:00+00:00,11.083334,307.19950,144.84512,12.533846,3.133333,300.66464,NaN,NaN
1,2016-03-22T08:00:00+00:00,11.100000,174.47252,150.80226,10.975560,2.900000,294.33660,NaN,NaN
2,2016-03-22T08:02:00+00:00,11.166666,360.01548,143.93522,14.223366,3.766667,300.83378,NaN,NaN
3,2016-03-22T08:06:00+00:00,11.233334,375.56660,128.84222,15.575274,2.683334,299.33326,NaN,NaN
4,2016-03-22T08:08:00+00:00,11.300000,376.88700,120.42222,15.897234,3.433333,295.83228,NaN,NaN

In [40]:
data_meteo_16.columns

Index(['Datetime', 'Ambient Temperature [ºC]', 'Global Radiation [W/m2]',
       'Direct Radiation [W/m2]', 'Ultraviolet [W/m2]', 'Wind Velocity [m/s]',
       'Wind Direction [º]', 'Precipitation [mm]',
       'Atmospheric pressure [hPa]'],
      dtype='object')

In [41]:
data_meteo_16 = data_meteo_16.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Direct Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [42]:
data_pv_16 = data_pv_16.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [43]:
data_meteo_16['Datetime'] = pd.to_datetime(data_meteo_16['Datetime'])
data_pv_16['Datetime'] = pd.to_datetime(data_pv_16['Datetime'])

In [44]:
# Sortting by date

data_meteo_16 = data_meteo_16.sort_values('Datetime').reset_index(drop=True)
data_pv_16 = data_pv_16.sort_values('Datetime').reset_index(drop=True)

In [45]:
final_dataset_16 = pd.merge (left = data_meteo_16, right = data_pv_16, left_on = 'Datetime', right_on = 'Datetime')

In [46]:
final_dataset_16.shape

(139080, 33)

In [47]:
final_dataset_16.drop(['Datetime', 'Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [48]:
final_dataset_16 = fill_gap (final_dataset_16, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [49]:
final_dataset_16.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,...,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000
mean,21.915041,437.300385,113.209025,26.515064,2.614318,191.581453,25.885418,2.085426,58.616335,27.585566,...,59.107307,26.159812,3.472106,94.541032,26.008123,3.039815,82.649881,29.957944,31.027824,29.173581
std,6.347771,315.737441,88.084871,19.561412,1.344107,90.957627,4.698047,1.791377,53.489842,3.095270,...,55.919735,3.664857,2.591010,70.833879,3.970745,2.261582,61.826733,7.941895,10.253741,10.041414
min,4.600000,1.418935,1.745721,0.558989,0.000000,0.000000,12.400000,0.000000,0.000000,10.298824,...,0.000000,13.110000,0.000000,0.000000,12.325000,0.000000,0.000000,4.527734,3.900000,2.800000
25%,16.500000,146.692500,55.736652,9.307752,1.633333,112.820280,26.250000,0.615000,13.333125,27.200000,...,12.682500,26.550000,0.927500,22.685625,26.550000,0.982500,23.312625,23.600000,22.400000,20.900000
50%,22.383334,401.623160,88.939464,22.673622,2.500000,200.162740,27.600000,1.605000,43.436250,28.150000,...,42.154500,27.250000,3.192500,90.045000,27.100000,2.690000,76.557500,31.100000,30.700000,27.700000
75%,27.433334,701.407920,145.257260,41.829000,3.450000,269.338260,28.950000,3.075000,88.497250,29.450000,...,88.740000,27.950000,6.015000,163.671000,28.150000,4.922500,136.062375,36.300000,39.800000,38.300000
max,38.300000,1413.023400,714.390160,83.990568,12.283334,359.997880,35.050000,8.105000,245.176250,35.300000,...,255.985500,35.150000,10.237500,298.423125,35.100000,10.235000,288.023250,51.100000,62.000000,62.100000

### Working with data from 2017

In [50]:
data_meteo_17 = pd.read_csv('dataset/meteo/sunlab-faro-meteo-2017.csv',sep=';')
data_pv_17 = pd.read_csv('dataset/pv/sunlab-faro-pv-2017.csv',sep=';')

In [51]:
data_meteo_17.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Diffuse Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2017-06-13T04:11:00+02:00,21.4,1.135318,1.688030,0.508061,4.150000,105.84458,0.0,1007.0334
1,2017-06-13T04:12:00+02:00,21.4,1.202852,1.693716,0.508069,2.850000,104.66702,0.0,1007.0334
2,2017-06-13T04:16:00+02:00,21.5,1.311066,1.710920,0.509157,3.683334,103.33748,0.0,1007.0668
3,2017-06-13T04:34:00+02:00,21.6,1.530087,1.683353,0.503610,3.433334,113.17200,0.0,1007.1334
4,2017-06-23T23:29:00+02:00,29.0,1.901296,2.147049,0.508236,0.566667,247.80524,0.0,1018.3000

In [52]:
data_pv_17.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2017-04-12T17:28:00+00:00,27.00,0.8050,21.735000,28.35,1.6850,47.769750,28.05,1.8500,51.892500,...,20.709000,27.55,1.6325,44.975375,27.35,1.8225,49.845375,30.8,34.9,33.0
1,2017-04-12T17:34:00+00:00,26.65,0.7450,19.854250,27.90,1.5150,42.268500,27.75,1.6900,46.897500,...,19.193125,27.35,1.4575,39.862625,27.25,1.6650,45.371250,30.4,34.1,32.9
2,2017-04-12T17:43:00+00:00,26.95,0.6575,17.719625,27.55,1.2425,34.230875,27.60,1.4375,39.675000,...,16.919375,27.30,1.1850,32.350500,27.60,1.4050,38.778000,30.5,34.1,32.8
3,2017-04-12T17:47:00+00:00,27.05,0.6200,16.771000,27.55,1.1150,30.718250,27.65,1.3100,36.221500,...,15.849375,27.30,1.0600,28.938000,28.85,0.9075,26.181375,30.5,33.9,32.3
4,2017-04-12T17:57:00+00:00,26.95,0.5200,14.014000,27.40,0.8200,22.468000,28.75,0.9725,27.959375,...,13.174375,27.65,0.7675,21.221375,27.15,0.9950,27.014250,30.0,33.0,30.6

In [53]:
data_meteo_17['Datetime'] = pd.to_datetime(data_meteo_17['Datetime'])
data_pv_17['Datetime'] = pd.to_datetime(data_pv_17['Datetime'])

In [54]:
data_meteo_17 = data_meteo_17.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [55]:
data_pv_17 = data_pv_17.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [56]:
final_dataset_17 = pd.merge (left = data_meteo_17, right = data_pv_17, left_on = 'Datetime', right_on = 'Datetime')

In [57]:
final_dataset_17.shape

(206957, 33)

In [58]:
final_dataset_17.drop(['Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [59]:
final_dataset_17 = fill_gap (final_dataset_17, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [60]:
# Sortting by date

data_meteo_17 = data_meteo_17.sort_values('Datetime').reset_index(drop=True)
data_pv_17 = data_pv_17.sort_values('Datetime').reset_index(drop=True)

In [61]:
final_dataset_17.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,...,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000,206957.000000
mean,21.351421,456.405075,127.603664,27.417600,2.636855,191.267172,26.197413,2.148532,60.574610,27.799351,...,60.779628,26.571459,3.631634,99.055561,26.323915,3.233513,88.413570,29.370250,30.600859,28.673248
std,5.593348,324.041851,104.583413,19.751333,1.266493,86.590004,4.555187,1.732976,51.537404,2.195098,...,53.700416,2.984500,2.624627,71.776468,3.603858,2.318345,63.918674,7.894537,9.933507,9.417011
min,3.000000,0.732156,1.626869,0.500453,0.000000,0.000000,12.750000,0.000000,0.000000,14.434277,...,0.000000,14.094531,0.000000,0.000000,14.265625,0.000000,0.000000,4.609375,3.000000,2.100000
25%,16.900000,159.744580,59.199452,9.703884,1.716667,116.698120,26.550000,0.692500,15.400250,27.350000,...,14.445000,26.700000,1.055000,26.273542,26.700000,1.085000,26.197000,23.600000,22.600000,21.300000
50%,21.400000,437.173120,97.970976,25.071114,2.550000,203.327220,27.950000,1.747500,48.369000,28.100000,...,46.630125,27.350000,3.445000,97.020000,27.350000,2.997500,85.115000,30.400000,30.800000,28.700000
75%,25.900000,725.581520,172.043880,43.315032,3.416666,263.011260,29.200000,3.225000,93.632500,29.000000,...,93.906000,28.000000,6.192500,168.752250,28.200000,5.152500,142.401750,35.300000,38.700000,36.200000
max,37.899996,1484.379800,715.146720,85.515376,10.300000,359.999200,34.700000,7.985000,244.295250,35.200000,...,250.965000,34.850000,10.237500,310.708125,34.150000,10.237500,296.681875,49.300000,58.500000,54.500000

### Savings last week of 2017 to final test

In [62]:
#Savings last week of year
final_dataset_17[final_dataset_17['Datetime'] > '2017-12-24'].to_csv('test_dataset_17.csv', sep=';', index=False)

In [63]:
# Dropping last week of year
final_dataset_17 = final_dataset_17.drop(final_dataset_17[final_dataset_17['Datetime'] > '2017-12-24'].index)
final_dataset_17.reset_index()

,index,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,0,2017-06-13 06:03:00,21.600000,71.765680,69.939760,5.399191,3.300000,129.816600,14.900000,0.160000,...,2.279875,15.100000,0.240000,3.612000,19.150000,0.242500,4.643875,23.8,22.9,22.7
1,1,2017-06-13 06:05:00,21.600000,115.415920,112.862560,8.290771,4.283334,130.504460,14.900000,0.177500,...,2.458500,15.000000,0.275000,4.152500,19.250000,0.295000,5.678750,23.8,23.0,22.7
2,2,2017-06-13 06:20:00,21.816666,109.468120,109.427260,8.246832,2.500000,123.678840,14.600000,0.367500,...,4.932000,14.950000,0.535000,7.971500,18.950000,0.610000,11.559500,24.0,23.2,23.0
3,3,2017-06-13 06:21:00,21.900000,107.936160,107.846820,8.153960,3.150000,125.288780,14.550000,0.375000,...,5.040000,14.925000,0.532500,7.934250,19.300000,0.607500,11.724750,24.0,23.2,23.0
4,4,2017-06-13 06:23:00,21.850000,99.323296,97.557976,7.782180,4.033333,130.167540,14.550000,0.417500,...,5.694000,15.062500,0.652500,9.722250,19.300000,0.765000,14.764500,24.0,23.2,23.0
5,5,2017-06-13 06:26:00,21.800002,106.696960,105.580720,8.206352,3.833333,119.996000,14.550000,0.420000,...,5.803500,15.081250,0.615000,9.348000,19.550000,0.757500,14.809125,24.0,23.3,23.1
6,6,2017-06-13 06:28:00,21.733332,96.899040,95.595024,7.316529,3.766667,121.501640,14.650000,0.365000,...,5.037000,15.115625,0.575000,8.682500,18.600000,0.675000,12.555000,24.1,23.3,23.1
7,7,2017-06-13 06:29:00,21.699998,125.444040,124.908460,9.386930,4.316667,121.325720,14.700000,0.360000,...,4.964000,15.107813,0.545000,8.256750,19.350000,0.782500,15.141375,24.1,23.3,23.2
8,8,2017-06-13 06:30:00,21.699998,136.781860,136.267300,10.409384,4.433333,124.331200,14.150000,0.320000,...,4.437750,15.003906,0.502500,7.587750,19.300000,0.645000,12.448500,24.1,23.3,23.2
9,9,2017-06-13 06:37:00,21.800002,142.467980,139.678540,10.463202,4.066667,136.493880,14.350000,0.290000,...,3.937625,15.101953,0.460000,6.854000,19.500000,0.517500,10.091250,24.1,23.4,23.2
10,10,2017-06-13 07:09:00,21.800002,104.847120,104.709980,8.503286,3.400000,118.500000,14.700000,0.540000,...,7.460250,15.550977,0.857500,13.034000,19.350000,0.957500,18.527625,24.5,23.7,23.4
11,11,2017-06-13 07:14:00,21.800002,173.896900,174.009500,13.183862,3.700000,138.998320,14.650000,0.490000,...,6.679500,16.000000,0.767500,12.280000,19.550000,0.880000,17.204000,24.6,23.8,23.5
12,12,2017-06-13 07:33:00,22.000000,211.657220,211.678040,15.742032,3.183333,130.166540,14.850000,0.617500,...,8.460375,19.400000,1.010000,19.594000,19.550000,1.132500,22.140375,25.5,24.7,24.4
13,13,2017-06-13 07:35:00,22.100000,248.201300,244.862260,18.255602,3.116667,126.527760,14.700000,0.585000,...,8.057500,19.350000,0.940000,18.189000,19.550000,1.125000,21.993750,25.5,24.7,24.4
14,14,2017-06-13 07:46:00,22.500000,238.898980,237.787160,17.139284,3.216667,115.877800,14.650000,0.610000,...,8.379000,19.350000,0.975000,18.866250,19.550000,1.177500,23.020125,25.4,24.7,24.5
15,15,2017-06-13 07:54:00,22.500000,370.151600,358.444080,24.731620,3.166667,117.474880,14.850000,0.440000,...,6.043125,20.100000,0.685000,13.768500,19.550000,0.777500,15.200125,25.3,24.5,24.3
16,16,2017-06-13 07:55:00,22.533332,391.694800,377.451880,25.701028,4.300000,122.665020,14.650000,0.425000,...,5.823375,19.650000,0.645000,12.674250,19.500000,0.737500,14.381250,25.2,24.5,24.2
17,17,2017-06-13 08:23:00,22.666666,338.271160,311.246000,21.970530,3.650000,117.739340,14.850000,0.835000,...,11.186250,19.600000,1.397500,27.391000,19.350000,1.422500,27.525375,26.0,25.3,24.9
18,18,2017-06-13 08:30:00,22.600000,659.492000,508.116360,39.816548,4.516667,137.835080,14.850000,0.882500,...,12.987000,19.600000,1.352500,26.509000,20.000000,1.522500,30.450000,25.8,25.1,24.7
19,19,2017-06-13 08:32:00,22.500000,509.030760,491.004120,33.785092,4.683334,146.820120,16.050000,1.020000,...,14.233750,19.450000,1.585000,30.828250,21.000000,1.722500,36.172500,25.9,25.2,24.7
20,20,2017-06-09 19:26:00,26.199998,1.378816,1.710339,0.509893,1.216667,319.518240,28.600000,0.030000,...,2.227875,29.150000,0.032500,0.947375,26.450000,0.147500,3.901375,31.5,29.9,30.1
21,21,2017-06-09 19:37:00,26.100000,1.308195,1.719521,0.504965,1.466667,313.432960,26.950000,0.030000,...,0.774000,27.650000,0.027500,0.760375,28.050000,0.032500,0.911625,31.2,29.7,29.7
22,22,2017-06-09 19:45:00,25.900000,1.584253,1.718015,0.507451,1.466667,322.359860,20.050000,0.032500,...,0.458000,24.650000,0.032500,0.801125,25.400000,0.035000,0.889000,31.1,29.6,29.4
23,23,2017-06-09 19:50:00,25.900000,1.620513,1.846163,0.503522,1.633333,329.500000,18.233333,0.054167,...,0.752333,22.800000,0.066667,1.393583,21.883333,0.078333,1.409417,30.9,29.4,29.2
24,24,2017-06-09 19:51:00,25.800002,1.696753,1.925953,0.503522,1.533333,317.671760,16.416667,0.075833,...,1.046667,20.950000,0.100833,1.986042,18.366667,0.121667,1.929833,30.9,29.4,29.1
25,25,2017-06-24 05:49:00,28.699998,143.450040,95.992864,9.485034,1.566667,341.234240,14.600000,0.097500,...,1.341000,19.100000,0.135000,2.578500,14.850000,0.165000,2.450250,27.3,26.4,26.2
26,26,2017-06-24 06:02:00,29.066668,231.034840,114.820960,12.499948,0.533333,358.397600,15.100000,0.155000,...,2.153250,19.250000,0.207500,3.994375,15.000000,0.285000,4.275000,27.8,27.1,26.9
27,27,2017-06-24 06:14:00,29.900000,276.278600,132.912000,14.799648,1.500000,23.121528,14.800000,0.275000,...,3.772375,19.250000,0.365000,7.026250,14.925000,0.467500,6.895625,28.9,28.3,28.3
28,28,2017-06-24 06:19:00,30.100000,298.335660,141.753840,15.822812,1.083333,26.744588,14.250000,0.342500,...,4.608000,19.550000,0.427500,8.357625,14.850000,0.595000,8.835750,29.1,28.4,28.3
29,29,2017-06-24 06:26:00,30.366666,343.315800,165.627700,17.701120,1.883333,26.625208,14.500000,0.417500,...,5.671625,19.550000,0.515000,10.068250,15.050000,0.755000,11.362750,29.4,28.6,28.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202288,206927,2017-05-28 05:47:00,18.699998,92.936696,91.362128,7.817823,0.366667,116.742380,19.250000,0.150000,...,2.167750,21.250000,0.245000,3.736250,21.175000,0.300000,4.440000,20.1,19.2,18.7
202289,206928,2017-05-28 05:56:00,18.900000,110.946220,108.062200,9.186108,0.733333,85.499392,19.150000,0.220000,...,3.129000,24.525000,0.337500,5.011875,24.237500,0.397500,5.863125,19.7,18.7,18.1
202290,206929,2017-07-01 16:21:00,26.100000,448.267960,59.485076,25.968874,3.716667,266.160820,26.800000,0.920000,...,23.295750,27.800000,3.700000,102.860000,27.300000,4.652500,127.013250,32.3,39.0,38.1
202291,206930,2017-05-28 06:08:00,19.100000,173.051260,147.720780,11.602370,0.783333,141.814200,19.300000,0.387500,...,5.438500,27.775000,0.567500,8.484125,14.850000,0.712500,10.580625,19.3,18.2,17.6
202292,206931,2017-07-01 16:32:00,26.100000,411.985800,60.163832,23.418028,2.500000,240.314720,26.850000,0.892500,...,22.670625,27.750000,3.380000,93.795000,27.850000,4.287500,119.406875,32.5,39.0,38.5
202293,206932,2017-05-28 06:14:00,19.366666,128.240080,119.213740,10.533910,0.683333,92.417776,19.550000,0.590000,...,8.249000,21.500000,0.737500,11.283750,15.000000,1.095000,16.425000,19.3,18.0,17.3
202294,206933,2017-05-28 06:15:00,19.400000,126.401960,119.284640,10.587728,0.933333,104.479780,19.550000,0.617500,...,8.650500,24.675000,0.755000,11.513750,15.100000,1.155000,17.440500,19.3,18.0,17.3
202295,206934,2017-07-01 16:38:00,26.000000,392.119840,59.832708,22.069100,4.066667,257.665680,26.800000,0.875000,...,22.352625,27.850000,3.187500,88.771875,27.650000,4.175000,115.438750,32.8,39.0,38.7
202296,206935,2017-05-28 06:23:00,19.400000,157.288440,151.218560,13.277884,1.300000,123.172620,19.400000,0.522500,...,7.336500,27.975000,0.637500,9.690000,19.600000,1.017500,19.943000,19.0,17.7,17.0
202297,206936,2017-07-01 16:54:00,25.816666,333.803500,55.550428,18.492438,2.083333,230.334660,26.700000,0.827500,...,21.132500,28.100000,2.672500,75.097250,27.950000,3.732500,104.323375,32.2,37.7,37.6
202298,206937,2017-05-28 06:33:00,19.500000,183.715040,174.900960,16.122374,0.850000,118.497700,19.400000,0.482500,...,6.665750,28.025000,0.722500,11.054250,19.500000,0.960000,18.720000,18.8,17.4,16.7
202299,206938,2017-07-01 17:04:00,26.000000,298.842740,54.826308,16.330492,2.850000,270.160680,26.550000,0.792500,...,20.225250,27.950000,2.370000,66.241500,27.900000,3.470000,96.813000,32.8,38.5,39.2
202300,206939,2017-05-28 06:51:00,19.900000,235.605980,231.519860,17.927910,1.200000,204.689940,19.300000,0.420000,...,6.045000,21.450000,0.650000,9.912500,20.250000,0.755000,15.288750,19.1,17.8,17.3
202301,206940,2017-06-03 05:30:00,18.699998,160.520200,37.398200,9.440390,2.366667,285.932100,14.850000,0.095000,...,1.728000,18.175000,0.110000,1.644500,14.900000,0.110000,1.639000,19.5,18.8,18.2
202302,206941,2017-06-03 05:33:00,18.800002,170.569360,38.221232,9.964972,1.683333,321.808100,14.750000,0.115000,...,1.927000,22.762500,0.130000,1.937000,15.000000,0.120000,1.800000,19.4,18.8,18.2
202303,206942,2017-07-01 17:37:00,26.500000,182.521660,44.690312,9.910228,3.250000,273.681620,26.800000,0.645000,...,16.159500,27.350000,1.390000,38.016500,26.450000,2.642500,69.894125,33.6,36.3,37.1
202304,206943,2017-07-01 17:43:00,26.433332,160.726800,41.053128,8.850704,3.366667,281.817240,26.800000,0.617500,...,15.410000,27.350000,1.220000,33.367000,27.800000,2.402500,66.789500,33.6,35.2,35.5
202305,206944,2017-05-28 07:36:00,20.400000,266.145560,254.550040,20.395640,1.950000,216.591980,19.400000,1.025000,...,18.864000,27.325000,1.112500,30.401750,19.700000,2.117500,41.714750,23.4,21.9,22.7
202306,206945,2017-07-01 17:51:00,26.449998,132.677500,38.853544,7.479012,3.166667,282.165400,26.800000,0.587500,...,14.499000,27.300000,1.005000,27.436500,28.000000,2.167500,60.690000,34.3,34.7,35.5
202307,206946,2017-07-01 17:56:00,26.400000,116.248200,37.112940,6.688374,2.300000,272.510100,26.700000,0.565000,...,13.776250,27.150000,0.880000,23.892000,27.350000,2.060000,56.341000,33.8,34.0,35.2
202308,206947,2017-05-28 07:48:00,20.300002,202.546800,195.040840,15.345116,2.983333,161.897680,19.450000,1.020000,...,18.671250,27.550000,1.487500,40.980625,27.350000,1.660000,45.401000,23.9,22.8,23.5
202309,206948,2017-07-01 17:59:00,26.300002,107.562220,35.476200,6.261864,2.133334,270.332880,26.700000,0.552500,...,13.375000,27.200000,0.812500,22.100000,27.450000,1.972500,54.145125,33.8,34.4,35.8
202310,206949,2017-07-01 18:08:00,26.316668,80.591288,33.144302,5.030981,2.766667,274.500000,26.800000,0.517500,...,12.259000,27.200000,0.620000,16.864000,27.400000,1.727500,47.333500,32.2,33.1,34.0
202311,206950,2017-05-28 08:07:00,20.600000,369.188720,361.479720,25.737076,3.400000,214.843840,19.600000,1.175000,...,21.860625,28.150000,1.762500,49.614375,28.650000,1.485000,42.545250,24.6,24.7,24.7
202312,206951,2017-07-01 18:14:00,26.199998,65.107996,29.519826,4.319071,2.483333,295.955560,26.850000,0.492500,...,11.836875,26.950000,0.517500,13.946625,26.850000,1.592500,42.758625,31.2,32.2,32.9
202313,206952,2017-07-01 18:41:00,25.699998,18.520666,16.183050,1.759812,1.500000,307.333800,26.700000,0.395000,...,8.610750,26.900000,0.275000,7.397500,27.000000,0.912500,24.637500,31.8,30.6,32.0
202314,206953,2017-07-01 18:57:00,25.100000,7.485613,6.993582,0.873425,0.816667,320.976440,26.300000,0.320000,...,6.823750,26.750000,0.232500,6.219375,27.000000,0.555000,14.985000,33.1,30.2,31.9
202315,206954,2017-07-01 19:13:00,24.400000,3.709006,4.063614,0.557801,1.550000,311.333320,26.200000,0.217500,...,4.808875,26.900000,0.167500,4.505750,26.800000,0.270000,7.236000,31.7,29.2,30.8
202316,206955,2017-07-01 19:52:00,22.800002,2.253112,2.480813,0.511687,1.283333,317.173920,22.350000,0.032500,...,0.538125,24.200000,0.032500,0.786500,24.500000,0.035000,0.857500,30.5,28.3,29.2
202317,206956,2017-07-01 19:59:00,22.600000,2.566325,2.512135,0.510884,1.150000,317.544220,22.350000,0.032500,...,0.538125,24.200000,0.032500,0.786500,24.500000,0.035000,0.857500,32.2,28.0,28.7

In [64]:
final_dataset_17.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2017-06-13 06:03:00,21.600000,71.765680,69.939760,5.399191,3.300000,129.81660,14.90,0.1600,2.384000,...,2.279875,15.1000,0.2400,3.61200,19.15,0.2425,4.643875,23.8,22.9,22.7
1,2017-06-13 06:05:00,21.600000,115.415920,112.862560,8.290771,4.283334,130.50446,14.90,0.1775,2.644750,...,2.458500,15.0000,0.2750,4.15250,19.25,0.2950,5.678750,23.8,23.0,22.7
2,2017-06-13 06:20:00,21.816666,109.468120,109.427260,8.246832,2.500000,123.67884,14.60,0.3675,5.365500,...,4.932000,14.9500,0.5350,7.97150,18.95,0.6100,11.559500,24.0,23.2,23.0
3,2017-06-13 06:21:00,21.900000,107.936160,107.846820,8.153960,3.150000,125.28878,14.55,0.3750,5.456250,...,5.040000,14.9250,0.5325,7.93425,19.30,0.6075,11.724750,24.0,23.2,23.0
4,2017-06-13 06:23:00,21.850000,99.323296,97.557976,7.782180,4.033333,130.16754,14.55,0.4175,6.074625,...,5.694000,15.0625,0.6525,9.72225,19.30,0.7650,14.764500,24.0,23.2,23.0

In [65]:
# Dropping datetime columns.
final_dataset_17.drop(['Datetime'], axis='columns', inplace=True)

In [66]:
final_dataset_17.head()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,21.600000,71.765680,69.939760,5.399191,3.300000,129.81660,14.90,0.1600,2.384000,23.65,...,2.279875,15.1000,0.2400,3.61200,19.15,0.2425,4.643875,23.8,22.9,22.7
1,21.600000,115.415920,112.862560,8.290771,4.283334,130.50446,14.90,0.1775,2.644750,23.65,...,2.458500,15.0000,0.2750,4.15250,19.25,0.2950,5.678750,23.8,23.0,22.7
2,21.816666,109.468120,109.427260,8.246832,2.500000,123.67884,14.60,0.3675,5.365500,23.95,...,4.932000,14.9500,0.5350,7.97150,18.95,0.6100,11.559500,24.0,23.2,23.0
3,21.900000,107.936160,107.846820,8.153960,3.150000,125.28878,14.55,0.3750,5.456250,23.95,...,5.040000,14.9250,0.5325,7.93425,19.30,0.6075,11.724750,24.0,23.2,23.0
4,21.850000,99.323296,97.557976,7.782180,4.033333,130.16754,14.55,0.4175,6.074625,24.00,...,5.694000,15.0625,0.6525,9.72225,19.30,0.7650,14.764500,24.0,23.2,23.0

### Saving data train

In [67]:
final_train_dataset = pd.concat([final_dataset_14, final_dataset_15, 
                                 final_dataset_16, final_dataset_17], axis = 0).reset_index(drop = True)
final_train_dataset.to_csv('train_dataset.csv', sep=';', index=False)