# PREPARING DATA

#### Vamos a ver los datos de los diferentes ficheros y prepararlos para que estén disponibles para trabajar con ellos. Cada uno de los datos anuales presentarán características diferentes por lo que su tratamiento será distinto.

## Importamos librerias

In [1]:
import pandas as pd
import numpy as np

## Apertura y visualización de los datos

### Trabajamos con los datos de 2014

In [2]:
# Guardando los datos en un dataframe

data_meteo_14 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2014.csv',
                            sep=';')
data_pv_14 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2014.csv',
                         sep=';')

In [3]:
# Vemos su forma

data_meteo_14.shape

(524863, 9)

In [4]:
data_pv_14.shape

(262145, 25)

In [5]:
# Visualizamos un ejemplo de los mismos

data_meteo_14.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Diffuse Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2014-02-28T04:59:00+00:00,13.783334,1.417539,1.672896,0.504882,2.116667,252.16572,NaN,NaN
1,2014-11-07T06:46:00+00:00,24.800002,193.118980,43.530248,10.453270,0.400000,159.51002,NaN,NaN
2,2014-11-07T06:54:00+00:00,25.249998,226.530840,46.454708,11.877266,0.600000,110.83258,NaN,NaN
3,2014-02-28T05:04:00+00:00,13.700000,1.183479,1.657202,0.505982,1.150000,211.66448,NaN,NaN
4,2014-11-07T07:03:00+00:00,24.699998,261.758280,49.932436,13.540898,0.466667,107.76016,NaN,NaN

In [6]:
data_pv_14.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2014-11-15T13:21:00+00:00,28.7,6.0100,172.48700,27.85,7.0300,195.785500,29.00,4.4125,127.962500,...,178.211625,27.50,7.0425,193.66875,28.45,4.3750,124.468750,36.4,36.4,29.5
1,2014-11-15T13:23:00+00:00,28.4,6.0375,171.46500,27.85,7.0200,195.507000,29.00,4.3925,127.382500,...,179.733000,27.30,7.0725,193.07925,28.35,4.3675,123.818625,36.7,36.9,29.6
2,2014-11-15T13:26:00+00:00,28.7,5.9975,172.12825,28.05,6.9925,196.139625,28.85,4.4025,127.012125,...,179.918125,27.60,7.0150,193.61400,28.35,4.3575,123.535125,35.3,36.0,28.7
3,2014-11-15T13:29:00+00:00,28.8,5.9300,170.78400,28.15,6.9300,195.079500,29.15,4.3175,125.855125,...,178.730625,27.60,6.9525,191.88900,28.45,4.2975,122.263875,34.5,35.0,28.1
4,2014-11-15T13:32:00+00:00,28.8,5.8050,167.18400,28.95,6.5525,189.694875,29.15,4.2200,123.013000,...,174.942500,27.75,6.7650,187.72875,28.35,4.2125,119.424375,34.3,34.7,28.0

In [7]:
# Vemos el nombre de las columnas para su posterior modificación

data_pv_14.columns

Index(['Datetime', 'A_Vertical - Voltage DC [V]',
       'A_Vertical - Current DC [A]', 'A_Vertical - Power DC [W]',
       'A_Optimal - Voltage DC [V]', 'A_Optimal - Current DC [A]',
       'A_Optimal - Power DC [W]', 'A_Horizontal - Voltage DC [V]',
       'A_Horizontal - Current DC [A]', 'A_Horizontal - Power DC [W]',
       'A_Vertical - Temperature [ºC]', 'A_Optimal - Temperature [ºC]',
       'A_Horizontal - Temperature [ºC]', 'B_Vertical - Voltage DC [V]',
       'B_Vertical - Current DC [A]', 'B_Vertical - Power DC [W]',
       'B_Optimal - Voltage DC [V]', 'B_Optimal - Current DC [A]',
       'B_Optimal - Power DC [W]', 'B_Horizontal - Voltage DC [V]',
       'B_Horizontal - Current DC [A]', 'B_Horizontal - Power DC [W]',
       'B_Vertical - Temperature [ºC]', 'B_Optimal - Temperature [ºC]',
       'B_Horizontal - Temperature [ºC]'],
      dtype='object')

In [8]:
# Renombramos las columnas

data_meteo_14 = data_meteo_14.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [9]:
data_pv_14 = data_pv_14.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [10]:
# Verificamos los cambios

data_meteo_14.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure
0,2014-02-28T04:59:00+00:00,13.783334,1.417539,1.672896,0.504882,2.116667,252.16572,NaN,NaN
1,2014-11-07T06:46:00+00:00,24.800002,193.118980,43.530248,10.453270,0.400000,159.51002,NaN,NaN
2,2014-11-07T06:54:00+00:00,25.249998,226.530840,46.454708,11.877266,0.600000,110.83258,NaN,NaN
3,2014-02-28T05:04:00+00:00,13.700000,1.183479,1.657202,0.505982,1.150000,211.66448,NaN,NaN
4,2014-11-07T07:03:00+00:00,24.699998,261.758280,49.932436,13.540898,0.466667,107.76016,NaN,NaN

In [11]:
data_pv_14.head()

,Datetime,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,A_Optimal_CDC,A_Optimal_PDC,A_Horizontal_VDC,A_Horizontal_CDC,A_Horizontal_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2014-11-15T13:21:00+00:00,28.7,6.0100,172.48700,27.85,7.0300,195.785500,29.00,4.4125,127.962500,...,178.211625,27.50,7.0425,193.66875,28.45,4.3750,124.468750,36.4,36.4,29.5
1,2014-11-15T13:23:00+00:00,28.4,6.0375,171.46500,27.85,7.0200,195.507000,29.00,4.3925,127.382500,...,179.733000,27.30,7.0725,193.07925,28.35,4.3675,123.818625,36.7,36.9,29.6
2,2014-11-15T13:26:00+00:00,28.7,5.9975,172.12825,28.05,6.9925,196.139625,28.85,4.4025,127.012125,...,179.918125,27.60,7.0150,193.61400,28.35,4.3575,123.535125,35.3,36.0,28.7
3,2014-11-15T13:29:00+00:00,28.8,5.9300,170.78400,28.15,6.9300,195.079500,29.15,4.3175,125.855125,...,178.730625,27.60,6.9525,191.88900,28.45,4.2975,122.263875,34.5,35.0,28.1
4,2014-11-15T13:32:00+00:00,28.8,5.8050,167.18400,28.95,6.5525,189.694875,29.15,4.2200,123.013000,...,174.942500,27.75,6.7650,187.72875,28.35,4.2125,119.424375,34.3,34.7,28.0

In [12]:
# Cambiamos el formato de la fecha

data_meteo_14['Datetime'] = pd.to_datetime(data_meteo_14['Datetime'], utc=True)
data_pv_14['Datetime'] = pd.to_datetime(data_pv_14['Datetime'], utc=True)

In [13]:
# Ordenamos los datos

data_meteo_14 = data_meteo_14.sort_values('Datetime').reset_index(drop=True)
data_pv_14 = data_pv_14.sort_values('Datetime').reset_index(drop=True)

In [14]:
# Unimos los datos mediante las fechas, para hacer coincidir los datos meteorológicos con los de producción
# ya que estos provienen de archivos diferentes y por tanto con merge los relacionamos por coincidencia de fecha

final_dataset_14 = pd.merge (left = data_meteo_14, right = data_pv_14, left_on = 'Datetime', right_on = 'Datetime')

In [15]:
# Vemos la forma de la tabla

final_dataset_14.shape

(262131, 33)

In [16]:
# Reseteamos los indices de la tabla

final_dataset_14.reset_index(drop=True)

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure,A_Vertical_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2014-01-01 07:41:00+00:00,9.700000,7.131149,6.929149,0.751824,0.700000,275.33384,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2,9.7,8.8
1,2014-01-01 07:42:00+00:00,9.700000,7.040442,6.847878,0.781930,0.666667,278.50306,NaN,NaN,NaN,...,NaN,18.30,0.130512,2.388366,NaN,NaN,NaN,10.2,9.7,8.8
2,2014-01-01 07:43:00+00:00,9.700000,6.594407,6.672844,0.813929,0.616667,284.66712,NaN,NaN,19.00,...,NaN,22.35,0.052500,1.173375,NaN,NaN,NaN,10.2,9.7,8.8
3,2014-01-01 07:44:00+00:00,9.700000,7.358729,6.752742,0.849919,0.666667,278.66666,NaN,NaN,18.65,...,0.900375,24.35,0.052500,1.278375,NaN,NaN,NaN,10.3,9.7,8.8
4,2014-01-01 07:45:00+00:00,9.700000,7.470711,7.181158,0.886891,0.633333,272.66636,NaN,NaN,18.65,...,0.992250,25.25,0.052500,1.325625,NaN,NaN,NaN,10.3,9.7,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262126,2014-12-31 17:30:00+00:00,12.600000,5.824658,5.729233,0.750715,1.116667,293.99914,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8,11.9,10.8
262127,2014-12-31 17:31:00+00:00,12.600000,5.625719,4.953854,0.727033,1.083333,304.33356,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7,11.8,10.7
262128,2014-12-31 17:32:00+00:00,12.533334,5.638842,5.304980,0.697024,1.050000,304.33368,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,11.8,10.6
262129,2014-12-31 17:33:00+00:00,12.500000,5.373980,5.200505,0.673228,1.116667,308.16662,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,11.7,10.6
262130,2014-12-31 17:34:00+00:00,12.500000,4.707419,4.852263,0.651809,1.066667,311.33050,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.5,11.7,10.5

In [17]:
# Eliminamos la columna de precipitación y presión atmosférica. No aportarán información valiosa

final_dataset_14.drop(['Precipitation', 'Atmospheric_pressure'], 
                                         axis='columns', inplace=True)

In [18]:
# Verificamos los cambios

final_dataset_14.columns

Index(['Datetime', 'Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity', 'Wind_direction',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'],
      dtype='object')

In [19]:
# Creamos un procedimiento para corregir los valores atipicos y rellenar los NaN

def fill_gap (dataset, columns_to_fill):
    
    # Rellenamos los NaN interpolando entre el valor anterior y posterior.
    
    try:
        dataset = dataset.interpolate(method='linear')
    except:
        dataset = dataset.fillna(method='bfill', limit=1)
    
    for nam_col in list(columns_to_fill):
        
        # Creamos las referencias para identificar los valores atipicos
        
        ref_low = dataset[nam_col].mean() - dataset[nam_col].std() * 3
        ref_high = dataset[nam_col].mean() + dataset[nam_col].std() * 3
        
        # Guardamos los indices de los valores atipicos
        
        indexes = dataset.index[(dataset[nam_col]<ref_low) & (dataset[nam_col]<ref_high)]
        
        # Cambiamos los valores atipicos por valores regulares. Tenemos cuidado con los indices extremos.
        # Si está dentro de los valores intermedios y está considerado outlier, se ejecuta le media entre
        # el anterior y el posterior, en cambio si está en los margenes del archivo, se asigna el valor del
        # más inmediato.
        
        for index in indexes:
                
            if 0 < index < len(dataset):
                dataset.loc[index, nam_col] = (np.mean([dataset.loc[index-1, nam_col], 
                                                        dataset.loc[index+1, nam_col]]))   
            elif index == 0:
                dataset.loc[index, nam_col] = dataset.loc[(index+1), nam_col]
                
            elif index == len(dataset):
                dataset.loc[index, nam_col] = dataset.loc[index-1, nam_col]

    # Si aún queda algún NaN, lo eliminamos.
    
    dataset = dataset.dropna(how='any')
    
    return dataset

In [20]:
# Aplicamos el procedimiento a los datos del 2014

final_dataset_14 = fill_gap (final_dataset_14, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [21]:
# Vemos una descripción de los datos

final_dataset_14.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,...,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000,246803.000000
mean,20.237762,460.336598,128.495229,28.257776,2.644534,207.272491,26.859830,2.177894,61.755329,27.821190,...,62.751612,26.962509,3.736135,102.543001,26.906294,3.325589,91.658136,28.826584,30.269232,28.411818
std,5.047223,313.706412,102.807406,19.387410,1.291603,83.741888,3.740519,1.720103,51.114862,1.714013,...,53.682714,2.622486,2.600702,71.180572,3.022016,2.283343,63.074114,7.105677,9.197326,8.729834
min,4.300000,0.876493,1.602785,0.500673,0.000000,0.000000,14.125000,0.000000,0.000000,13.162500,...,0.000000,14.267736,0.000000,0.000000,14.277415,0.000000,0.000000,4.810156,4.200000,3.200000
25%,16.200000,178.168850,62.582916,11.367816,1.716667,138.987140,26.700000,0.742500,17.382750,27.050000,...,16.513125,26.950000,1.270000,33.818562,26.850000,1.292500,33.008063,23.500000,22.800000,21.500000
50%,20.400000,435.300800,98.210056,25.549254,2.566667,226.332300,28.200000,1.777500,50.150000,27.950000,...,49.616625,27.450000,3.525000,99.650250,27.600000,3.057500,87.072500,29.500000,30.400000,28.200000
75%,23.949998,727.901640,161.898190,44.089316,3.466667,269.838730,29.300000,3.265000,94.800500,28.950000,...,96.437250,28.100000,6.245000,170.967375,28.400000,5.262500,146.758750,34.100000,37.600000,35.400000
max,35.399996,1438.887200,776.552080,81.365264,9.833334,359.998440,36.800000,8.095000,228.279000,36.900000,...,244.876500,36.550000,10.237500,303.030000,36.000000,10.237500,297.399375,55.100000,56.900000,105.800000

### Trabajamos con los datos del año 2015

Repetimos el mismo procedimiento que los valores anteriores.

In [22]:
data_meteo_15 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2015.csv',
                            sep=';')
data_pv_15 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2015.csv',
                         sep=';')

In [23]:
data_meteo_15.shape

(437159, 9)

In [24]:
data_pv_15.shape

(242735, 25)

In [25]:
data_meteo_15 = data_meteo_15.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [26]:
data_pv_15 = data_pv_15.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [27]:
data_meteo_15['Datetime'] = pd.to_datetime(data_meteo_15['Datetime'], utc=True)
data_pv_15['Datetime'] = pd.to_datetime(data_pv_15['Datetime'], utc=True)

In [28]:
# Ordenamos por fecha

data_meteo_15 = data_meteo_15.sort_values('Datetime').reset_index(drop=True)
data_pv_15 = data_pv_15.sort_values('Datetime').reset_index(drop=True)

In [29]:
final_dataset_15 = pd.merge (left = data_meteo_15, right = data_pv_15, left_on = 'Datetime', right_on = 'Datetime')

In [30]:
final_dataset_15.shape

(225510, 33)

In [31]:
final_dataset_15.drop(['Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [32]:
final_dataset_15 = fill_gap (final_dataset_15, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [33]:
final_dataset_15.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,...,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000,212517.000000
mean,21.269369,487.107588,134.148671,29.265542,2.652914,196.677476,26.580888,2.173304,61.408592,27.685668,...,61.930230,26.710616,3.835768,104.815051,26.749491,3.385949,93.336437,29.578190,31.327292,29.448030
std,5.426458,311.940711,102.875597,18.934495,1.287432,83.841613,4.136046,1.688191,50.467756,1.652957,...,52.725686,2.985211,2.631899,71.901197,3.439758,2.261031,62.660805,7.306542,9.569997,9.026023
min,3.500000,3.361539,2.979969,0.592357,0.000000,0.000000,12.800000,0.000000,0.000000,12.725000,...,0.000000,14.178680,0.000000,0.000000,14.184375,0.000000,0.000000,3.557617,2.800000,2.200000
25%,17.383334,200.955120,65.727684,12.329286,1.716667,127.171780,26.700000,0.780000,17.953750,27.000000,...,16.689375,26.850000,1.317500,35.164000,26.850000,1.327500,33.807250,24.500000,23.800000,22.500000
50%,21.383334,477.207600,104.268800,27.354468,2.583333,216.000160,28.050000,1.795000,50.300625,27.750000,...,49.204125,27.350000,3.680000,103.393125,27.600000,3.232500,92.112250,30.600000,31.900000,29.900000
75%,25.199998,760.285360,165.520200,45.375292,3.466667,258.746040,29.200000,3.225000,93.828750,28.700000,...,94.929750,28.000000,6.420000,174.873625,28.450000,5.325000,148.878750,35.200000,39.100000,36.500000
max,37.166668,1421.328200,720.352560,84.266016,9.700002,359.999160,34.400000,7.997500,236.664000,34.650000,...,243.975000,34.900000,10.237500,302.006250,34.450000,10.237500,300.982500,48.400000,55.500000,53.300000

### Trabajamos con los datos de 2016

Repetimos el mismo procedimiento que los valores anteriores.

In [34]:
data_meteo_16 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2016.csv',
                            sep=';')
data_pv_16 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2016.csv',
                         sep=';')

In [35]:
data_meteo_16.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Direct Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2016-03-22T07:58:00+00:00,11.083334,307.19950,144.84512,12.533846,3.133333,300.66464,NaN,NaN
1,2016-03-22T08:00:00+00:00,11.100000,174.47252,150.80226,10.975560,2.900000,294.33660,NaN,NaN
2,2016-03-22T08:02:00+00:00,11.166666,360.01548,143.93522,14.223366,3.766667,300.83378,NaN,NaN
3,2016-03-22T08:06:00+00:00,11.233334,375.56660,128.84222,15.575274,2.683334,299.33326,NaN,NaN
4,2016-03-22T08:08:00+00:00,11.300000,376.88700,120.42222,15.897234,3.433333,295.83228,NaN,NaN

In [36]:
data_pv_16.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2016-02-11T15:34:00+00:00,28.50,1.1275,32.13375,29.40,1.5725,46.231500,27.10,1.4625,39.63375,...,31.050000,27.55,1.5675,43.184625,27.25,1.4125,38.490625,24.5,22.8,22.5
1,2016-06-10T13:23:00+00:00,29.50,1.7725,52.28875,34.20,0.8050,27.531000,28.50,4.2500,121.12500,...,51.051000,28.15,3.8550,108.518250,28.10,4.1750,117.317500,37.0,42.3,43.5
2,2016-02-11T10:41:00+00:00,30.20,1.4775,44.62050,29.25,2.4250,70.931250,29.25,2.2850,66.83625,...,44.846875,28.70,2.3825,68.377750,28.95,2.2275,64.486125,27.4,25.7,24.9
3,2016-06-10T13:25:00+00:00,29.50,1.9775,58.33625,34.45,0.8100,27.904500,28.30,5.0950,144.18850,...,56.889875,27.70,4.6775,129.566750,28.35,4.9400,140.049000,37.2,43.3,44.4
4,2016-02-11T10:44:00+00:00,29.75,1.4450,42.98875,29.25,2.2375,65.446875,30.15,1.9200,57.88800,...,42.333000,28.30,2.2000,62.260000,28.70,1.9550,56.108500,27.1,25.3,24.6

In [37]:
data_meteo_16.shape

(399744, 9)

In [38]:
data_pv_16.shape

(177772, 25)

In [39]:
data_meteo_16.columns

Index(['Datetime', 'Ambient Temperature [ºC]', 'Global Radiation [W/m2]',
       'Direct Radiation [W/m2]', 'Ultraviolet [W/m2]', 'Wind Velocity [m/s]',
       'Wind Direction [º]', 'Precipitation [mm]',
       'Atmospheric pressure [hPa]'],
      dtype='object')

In [40]:
data_meteo_16 = data_meteo_16.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Direct Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [41]:
data_pv_16 = data_pv_16.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [42]:
data_meteo_16['Datetime'] = pd.to_datetime(data_meteo_16['Datetime'], utc=True)
data_pv_16['Datetime'] = pd.to_datetime(data_pv_16['Datetime'], utc=True)

In [43]:
# Ordenamos por fechas

data_meteo_16 = data_meteo_16.sort_values('Datetime').reset_index(drop=True)
data_pv_16 = data_pv_16.sort_values('Datetime').reset_index(drop=True)

In [44]:
final_dataset_16 = pd.merge (left = data_meteo_16, right = data_pv_16, left_on = 'Datetime', right_on = 'Datetime')

In [45]:
final_dataset_16.shape

(139080, 33)

In [46]:
final_dataset_16.drop(['Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [47]:
final_dataset_16 = fill_gap (final_dataset_16, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [48]:
final_dataset_16.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,...,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000,131260.000000
mean,22.085024,460.908646,118.730844,27.913256,2.677501,190.873862,26.375847,2.198206,61.906732,28.034366,...,62.433394,26.671988,3.666285,99.953900,26.482352,3.204946,87.293427,30.497611,31.694915,29.761685
std,6.369448,308.973982,87.468032,19.231978,1.333220,89.519529,4.302602,1.780013,53.246956,2.352522,...,55.792267,2.956503,2.536318,69.201160,3.453274,2.219321,60.516570,7.720138,10.079868,9.936948
min,4.700001,1.917793,1.745721,0.731041,0.000000,0.000000,12.450000,0.000000,0.000000,10.298824,...,0.000000,14.290078,0.000000,0.000000,14.325000,0.000000,0.000000,4.581934,4.100000,2.900000
25%,16.500000,182.771405,60.834308,11.284319,1.716667,113.678530,26.700000,0.747500,16.985687,27.350000,...,15.648750,26.700000,1.227500,32.104875,26.650000,1.222500,30.375000,24.500000,23.200000,21.500000
50%,22.733332,432.580180,93.195560,24.392071,2.566667,197.832170,27.800000,1.767500,48.641250,28.250000,...,47.150750,27.350000,3.520000,98.760563,27.150000,2.927500,83.131250,31.700000,31.500000,28.700000
75%,27.633334,720.156500,150.511940,43.222380,3.500000,266.474910,29.050000,3.192500,91.932250,29.500000,...,92.792250,28.000000,6.142500,166.767875,28.250000,5.077500,139.917094,36.600000,40.300000,38.700000
max,38.300000,1413.023400,714.390160,83.990568,12.283334,359.997880,35.050000,8.105000,245.176250,35.300000,...,255.985500,35.150000,10.237500,298.423125,35.100000,10.235000,288.023250,51.100000,62.000000,62.100000

### Trabajamos con los datos de 2017

Repetimos el mismo procedimiento que los valores anteriores.

In [49]:
data_meteo_17 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2017.csv',
                            sep=';')
data_pv_17 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2017.csv',
                         sep=';')

In [50]:
data_meteo_17.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Diffuse Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2017-06-13T04:11:00+02:00,21.4,1.135318,1.688030,0.508061,4.150000,105.84458,0.0,1007.0334
1,2017-06-13T04:12:00+02:00,21.4,1.202852,1.693716,0.508069,2.850000,104.66702,0.0,1007.0334
2,2017-06-13T04:16:00+02:00,21.5,1.311066,1.710920,0.509157,3.683334,103.33748,0.0,1007.0668
3,2017-06-13T04:34:00+02:00,21.6,1.530087,1.683353,0.503610,3.433334,113.17200,0.0,1007.1334
4,2017-06-23T23:29:00+02:00,29.0,1.901296,2.147049,0.508236,0.566667,247.80524,0.0,1018.3000

In [51]:
data_pv_17.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2017-04-12T17:28:00+00:00,27.00,0.8050,21.735000,28.35,1.6850,47.769750,28.05,1.8500,51.892500,...,20.709000,27.55,1.6325,44.975375,27.35,1.8225,49.845375,30.8,34.9,33.0
1,2017-04-12T17:34:00+00:00,26.65,0.7450,19.854250,27.90,1.5150,42.268500,27.75,1.6900,46.897500,...,19.193125,27.35,1.4575,39.862625,27.25,1.6650,45.371250,30.4,34.1,32.9
2,2017-04-12T17:43:00+00:00,26.95,0.6575,17.719625,27.55,1.2425,34.230875,27.60,1.4375,39.675000,...,16.919375,27.30,1.1850,32.350500,27.60,1.4050,38.778000,30.5,34.1,32.8
3,2017-04-12T17:47:00+00:00,27.05,0.6200,16.771000,27.55,1.1150,30.718250,27.65,1.3100,36.221500,...,15.849375,27.30,1.0600,28.938000,28.85,0.9075,26.181375,30.5,33.9,32.3
4,2017-04-12T17:57:00+00:00,26.95,0.5200,14.014000,27.40,0.8200,22.468000,28.75,0.9725,27.959375,...,13.174375,27.65,0.7675,21.221375,27.15,0.9950,27.014250,30.0,33.0,30.6

In [52]:
data_meteo_17['Datetime'] = pd.to_datetime(data_meteo_17['Datetime'], utc=True)
data_pv_17['Datetime'] = pd.to_datetime(data_pv_17['Datetime'], utc=True)

In [53]:
data_meteo_17 = data_meteo_17.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [54]:
data_pv_17 = data_pv_17.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [55]:
data_meteo_17.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure
0,2017-06-13 02:11:00+00:00,21.4,1.135318,1.688030,0.508061,4.150000,105.84458,0.0,1007.0334
1,2017-06-13 02:12:00+00:00,21.4,1.202852,1.693716,0.508069,2.850000,104.66702,0.0,1007.0334
2,2017-06-13 02:16:00+00:00,21.5,1.311066,1.710920,0.509157,3.683334,103.33748,0.0,1007.0668
3,2017-06-13 02:34:00+00:00,21.6,1.530087,1.683353,0.503610,3.433334,113.17200,0.0,1007.1334
4,2017-06-23 21:29:00+00:00,29.0,1.901296,2.147049,0.508236,0.566667,247.80524,0.0,1018.3000

In [56]:
data_pv_17.head()

,Datetime,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,A_Optimal_CDC,A_Optimal_PDC,A_Horizontal_VDC,A_Horizontal_CDC,A_Horizontal_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2017-04-12 17:28:00+00:00,27.00,0.8050,21.735000,28.35,1.6850,47.769750,28.05,1.8500,51.892500,...,20.709000,27.55,1.6325,44.975375,27.35,1.8225,49.845375,30.8,34.9,33.0
1,2017-04-12 17:34:00+00:00,26.65,0.7450,19.854250,27.90,1.5150,42.268500,27.75,1.6900,46.897500,...,19.193125,27.35,1.4575,39.862625,27.25,1.6650,45.371250,30.4,34.1,32.9
2,2017-04-12 17:43:00+00:00,26.95,0.6575,17.719625,27.55,1.2425,34.230875,27.60,1.4375,39.675000,...,16.919375,27.30,1.1850,32.350500,27.60,1.4050,38.778000,30.5,34.1,32.8
3,2017-04-12 17:47:00+00:00,27.05,0.6200,16.771000,27.55,1.1150,30.718250,27.65,1.3100,36.221500,...,15.849375,27.30,1.0600,28.938000,28.85,0.9075,26.181375,30.5,33.9,32.3
4,2017-04-12 17:57:00+00:00,26.95,0.5200,14.014000,27.40,0.8200,22.468000,28.75,0.9725,27.959375,...,13.174375,27.65,0.7675,21.221375,27.15,0.9950,27.014250,30.0,33.0,30.6

In [57]:
final_dataset_17 = pd.merge (left = data_meteo_17, right = data_pv_17, left_on = 'Datetime', right_on = 'Datetime')

In [58]:
# Ordenamos por fecha

data_meteo_17 = data_meteo_17.sort_values('Datetime').reset_index(drop=True)
data_pv_17 = data_pv_17.sort_values('Datetime').reset_index(drop=True)

In [59]:
final_dataset_17.shape

(206957, 33)

In [60]:
final_dataset_17.drop(['Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [61]:
final_dataset_17.shape

(206957, 31)

In [62]:
final_dataset_17 = fill_gap (final_dataset_17, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [63]:
final_dataset_17.shape

(203097, 31)

In [64]:
final_dataset_17.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,...,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000
mean,21.399671,462.741953,129.134046,27.797956,2.651215,191.044225,26.305041,2.179694,61.484313,27.877210,...,61.673561,26.699803,3.690305,100.694488,26.394063,3.284258,89.842888,29.541031,30.813325,28.858751
std,5.586697,323.184808,104.771711,19.711869,1.261512,86.131858,4.500542,1.734413,51.597572,2.078557,...,53.777465,2.803538,2.614220,71.451994,3.582354,2.310777,63.677210,7.820928,9.866402,9.366542
min,3.000000,0.732156,1.626869,0.501036,0.000000,0.000000,12.450000,0.000000,0.000000,14.434277,...,0.000000,14.345508,0.000000,0.000000,14.337500,0.000000,0.000000,4.609375,3.000000,2.100000
25%,17.000000,167.679020,60.578404,10.186330,1.750000,116.856400,26.650000,0.725000,16.317500,27.350000,...,15.168000,26.750000,1.140000,28.938000,26.750000,1.147500,28.093375,23.800000,22.900000,21.500000
50%,21.433334,447.357880,99.255776,25.675188,2.566667,202.842860,28.000000,1.790000,49.886125,28.100000,...,48.025000,27.350000,3.550000,99.928125,27.350000,3.072500,87.188000,30.500000,31.100000,29.000000
75%,25.933334,731.379680,174.083680,43.740232,3.416667,261.936860,29.250000,3.260000,94.696875,29.050000,...,95.215000,28.050000,6.237500,169.830000,28.200000,5.200000,143.592000,35.400000,38.800000,36.300000
max,37.899996,1484.379800,715.146720,85.515376,10.300000,359.999200,34.700000,7.985000,244.295250,35.200000,...,250.965000,34.850000,10.237500,310.708125,34.150000,10.237500,296.681875,49.300000,58.500000,54.500000

### Concatenamos todos los dataset y dividimos entre entrenamiento y test.

Para poder entrenar y determinar si el modelo es valido y adecuado, haremos una separación del 20% de los datos para testear y del 80% para entrenar.

In [65]:
final_dataset = pd.concat([final_dataset_14, final_dataset_15, 
                                 final_dataset_16, final_dataset_17], axis = 0).reset_index(drop = True)

In [66]:
from sklearn.model_selection import train_test_split

final_train_dataset, final_test_dataset = train_test_split(final_dataset, test_size = 0.20)

In [67]:
# Desordenamos el DataFrame de entrenamiento para asegurarnos de que no existe estacionalidad en los datos

from sklearn.utils import shuffle

final_train_dataset = shuffle(final_train_dataset)

### Guardamos los dataset en archivos para su posterior uso

In [68]:
final_train_dataset.to_csv('train_dataset.csv', sep=';', index=False)
final_test_dataset.to_csv('test_dataset.csv', sep=';', index=False)