# PREPARING DATA

#### We are going to see the data of the different files and prepare them to be able to work with them, since as we have seen in the previous step, each one of them has different characteristics.

## Importing libraries

In [127]:
import pandas as pd
import numpy as np

## Collecting and visualizing data

### Working with data from 2014

In [128]:
# Saving data in a dataframe

data_meteo_14 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2014.csv',
                            sep=';')
data_pv_14 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2014.csv',
                         sep=';')

In [129]:
# Seeing shape

data_meteo_14.shape

(524863, 9)

In [130]:
data_pv_14.shape

(262145, 25)

In [131]:
# Seeing a example

data_meteo_14.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Diffuse Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2014-02-28T04:59:00+00:00,13.783334,1.417539,1.672896,0.504882,2.116667,252.16572,NaN,NaN
1,2014-11-07T06:46:00+00:00,24.800002,193.118980,43.530248,10.453270,0.400000,159.51002,NaN,NaN
2,2014-11-07T06:54:00+00:00,25.249998,226.530840,46.454708,11.877266,0.600000,110.83258,NaN,NaN
3,2014-02-28T05:04:00+00:00,13.700000,1.183479,1.657202,0.505982,1.150000,211.66448,NaN,NaN
4,2014-11-07T07:03:00+00:00,24.699998,261.758280,49.932436,13.540898,0.466667,107.76016,NaN,NaN

In [132]:
data_pv_14.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2014-11-15T13:21:00+00:00,28.7,6.0100,172.48700,27.85,7.0300,195.785500,29.00,4.4125,127.962500,...,178.211625,27.50,7.0425,193.66875,28.45,4.3750,124.468750,36.4,36.4,29.5
1,2014-11-15T13:23:00+00:00,28.4,6.0375,171.46500,27.85,7.0200,195.507000,29.00,4.3925,127.382500,...,179.733000,27.30,7.0725,193.07925,28.35,4.3675,123.818625,36.7,36.9,29.6
2,2014-11-15T13:26:00+00:00,28.7,5.9975,172.12825,28.05,6.9925,196.139625,28.85,4.4025,127.012125,...,179.918125,27.60,7.0150,193.61400,28.35,4.3575,123.535125,35.3,36.0,28.7
3,2014-11-15T13:29:00+00:00,28.8,5.9300,170.78400,28.15,6.9300,195.079500,29.15,4.3175,125.855125,...,178.730625,27.60,6.9525,191.88900,28.45,4.2975,122.263875,34.5,35.0,28.1
4,2014-11-15T13:32:00+00:00,28.8,5.8050,167.18400,28.95,6.5525,189.694875,29.15,4.2200,123.013000,...,174.942500,27.75,6.7650,187.72875,28.35,4.2125,119.424375,34.3,34.7,28.0

In [133]:
# Looking columns

data_pv_14.columns

Index(['Datetime', 'A_Vertical - Voltage DC [V]',
       'A_Vertical - Current DC [A]', 'A_Vertical - Power DC [W]',
       'A_Optimal - Voltage DC [V]', 'A_Optimal - Current DC [A]',
       'A_Optimal - Power DC [W]', 'A_Horizontal - Voltage DC [V]',
       'A_Horizontal - Current DC [A]', 'A_Horizontal - Power DC [W]',
       'A_Vertical - Temperature [ºC]', 'A_Optimal - Temperature [ºC]',
       'A_Horizontal - Temperature [ºC]', 'B_Vertical - Voltage DC [V]',
       'B_Vertical - Current DC [A]', 'B_Vertical - Power DC [W]',
       'B_Optimal - Voltage DC [V]', 'B_Optimal - Current DC [A]',
       'B_Optimal - Power DC [W]', 'B_Horizontal - Voltage DC [V]',
       'B_Horizontal - Current DC [A]', 'B_Horizontal - Power DC [W]',
       'B_Vertical - Temperature [ºC]', 'B_Optimal - Temperature [ºC]',
       'B_Horizontal - Temperature [ºC]'],
      dtype='object')

In [134]:
# Renaming columns

data_meteo_14 = data_meteo_14.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [135]:
data_pv_14 = data_pv_14.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [136]:
# Checking renamed

data_meteo_14.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure
0,2014-02-28T04:59:00+00:00,13.783334,1.417539,1.672896,0.504882,2.116667,252.16572,NaN,NaN
1,2014-11-07T06:46:00+00:00,24.800002,193.118980,43.530248,10.453270,0.400000,159.51002,NaN,NaN
2,2014-11-07T06:54:00+00:00,25.249998,226.530840,46.454708,11.877266,0.600000,110.83258,NaN,NaN
3,2014-02-28T05:04:00+00:00,13.700000,1.183479,1.657202,0.505982,1.150000,211.66448,NaN,NaN
4,2014-11-07T07:03:00+00:00,24.699998,261.758280,49.932436,13.540898,0.466667,107.76016,NaN,NaN

In [137]:
data_pv_14.head()

,Datetime,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,A_Optimal_CDC,A_Optimal_PDC,A_Horizontal_VDC,A_Horizontal_CDC,A_Horizontal_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2014-11-15T13:21:00+00:00,28.7,6.0100,172.48700,27.85,7.0300,195.785500,29.00,4.4125,127.962500,...,178.211625,27.50,7.0425,193.66875,28.45,4.3750,124.468750,36.4,36.4,29.5
1,2014-11-15T13:23:00+00:00,28.4,6.0375,171.46500,27.85,7.0200,195.507000,29.00,4.3925,127.382500,...,179.733000,27.30,7.0725,193.07925,28.35,4.3675,123.818625,36.7,36.9,29.6
2,2014-11-15T13:26:00+00:00,28.7,5.9975,172.12825,28.05,6.9925,196.139625,28.85,4.4025,127.012125,...,179.918125,27.60,7.0150,193.61400,28.35,4.3575,123.535125,35.3,36.0,28.7
3,2014-11-15T13:29:00+00:00,28.8,5.9300,170.78400,28.15,6.9300,195.079500,29.15,4.3175,125.855125,...,178.730625,27.60,6.9525,191.88900,28.45,4.2975,122.263875,34.5,35.0,28.1
4,2014-11-15T13:32:00+00:00,28.8,5.8050,167.18400,28.95,6.5525,189.694875,29.15,4.2200,123.013000,...,174.942500,27.75,6.7650,187.72875,28.35,4.2125,119.424375,34.3,34.7,28.0

In [138]:
# Changing the time format to UTC

data_meteo_14['Datetime'] = pd.to_datetime(data_meteo_14['Datetime'], utc=True)
data_pv_14['Datetime'] = pd.to_datetime(data_pv_14['Datetime'], utc=True)

In [139]:
# Sortting by date

data_meteo_14 = data_meteo_14.sort_values('Datetime').reset_index(drop=True)
data_pv_14 = data_pv_14.sort_values('Datetime').reset_index(drop=True)

In [140]:
# Joining both tables by date

final_dataset_14 = pd.merge (left = data_meteo_14, right = data_pv_14, left_on = 'Datetime', right_on = 'Datetime')

In [141]:
# Seeing the shape

final_dataset_14.shape

(262131, 33)

In [142]:
# Resetting indexes

final_dataset_14.reset_index()

,index,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,0,2014-01-01 07:41:00+00:00,9.700000,7.131149,6.929149,0.751824,0.700000,275.33384,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2,9.7,8.8
1,1,2014-01-01 07:42:00+00:00,9.700000,7.040442,6.847878,0.781930,0.666667,278.50306,NaN,NaN,...,NaN,18.30,0.130512,2.388366,NaN,NaN,NaN,10.2,9.7,8.8
2,2,2014-01-01 07:43:00+00:00,9.700000,6.594407,6.672844,0.813929,0.616667,284.66712,NaN,NaN,...,NaN,22.35,0.052500,1.173375,NaN,NaN,NaN,10.2,9.7,8.8
3,3,2014-01-01 07:44:00+00:00,9.700000,7.358729,6.752742,0.849919,0.666667,278.66666,NaN,NaN,...,0.900375,24.35,0.052500,1.278375,NaN,NaN,NaN,10.3,9.7,8.8
4,4,2014-01-01 07:45:00+00:00,9.700000,7.470711,7.181158,0.886891,0.633333,272.66636,NaN,NaN,...,0.992250,25.25,0.052500,1.325625,NaN,NaN,NaN,10.3,9.7,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262126,262126,2014-12-31 17:30:00+00:00,12.600000,5.824658,5.729233,0.750715,1.116667,293.99914,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8,11.9,10.8
262127,262127,2014-12-31 17:31:00+00:00,12.600000,5.625719,4.953854,0.727033,1.083333,304.33356,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.7,11.8,10.7
262128,262128,2014-12-31 17:32:00+00:00,12.533334,5.638842,5.304980,0.697024,1.050000,304.33368,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,11.8,10.6
262129,262129,2014-12-31 17:33:00+00:00,12.500000,5.373980,5.200505,0.673228,1.116667,308.16662,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,11.7,10.6
262130,262130,2014-12-31 17:34:00+00:00,12.500000,4.707419,4.852263,0.651809,1.066667,311.33050,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.5,11.7,10.5

In [143]:
# Dropping Datetime, Precipitation and Atmospheric pressure. They do not provide information.

final_dataset_14.drop(['Datetime', 'Precipitation', 'Atmospheric_pressure'], 
                                         axis='columns', inplace=True)

In [144]:
# Describing data. There are outliers. It is necesary to delete them.

final_dataset_14.columns

Index(['Ambient_Temperature', 'Global_Radiation', 'Diffuse_Radiation',
       'Ultraviolet', 'Wind_Velocity', 'Wind_direction', 'A_Vertical_VDC',
       'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC', 'A_Optimal_CDC',
       'A_Optimal_PDC', 'A_Horizontal_VDC', 'A_Horizontal_CDC',
       'A_Horizontal_PDC', 'A_Vertical_Temperature', 'A_Optimal_Temperature',
       'A_Horizontal_Temperature', 'B_Vertical_VDC', 'B_Vertical_CDC',
       'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC', 'B_Optimal_PDC',
       'B_Horizontal_VDC', 'B_Horizontal_CDC', 'B_Horizontal_PDC',
       'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'],
      dtype='object')

In [145]:
# Procedure to fill gaps using mean between previus and next data.

def fill_gap (dataset, columns_to_fill):
    
    # Fill NaN interpolating between before and after values
    
    try:
        dataset = dataset.interpolate(method='linear')
    except:
        dataset = dataset.fillna(method='bfill', limit=1)
    
    for nam_col in list(columns_to_fill):
        
        # Reference to considere outliers.
        
        ref_low = dataset[nam_col].mean() - dataset[nam_col].std() * 3
        ref_high = dataset[nam_col].mean() + dataset[nam_col].std() * 3
        
        # Saving index of outliers.
        
        indexes = dataset.index[(dataset[nam_col]<ref_low) & (dataset[nam_col]<ref_high)]
        
        # Changing outliers for a regular data. Taking care with extreme indexes.
        for index in indexes:
                
            if 0 < index < len(dataset):
                dataset.loc[index, nam_col] = (np.mean([dataset.loc[index-1, nam_col], 
                                                        dataset.loc[index+1, nam_col]]))   
            elif index == 0:
                dataset.loc[index, nam_col] = dataset.loc[(index+1), nam_col]
                
            elif index == len(dataset):
                dataset.loc[index, nam_col] = dataset.loc[index-1, nam_col]

    # If there are nay NaN, drop row
    
    dataset = dataset.dropna(how='any')
    
    return dataset

In [146]:
# Applying procedure

final_dataset_14 = fill_gap (final_dataset_14, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [147]:
# Describing data

final_dataset_14.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,...,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000,262070.000000
mean,20.023628,438.848087,122.966855,26.953351,2.580107,207.405046,26.410945,2.069233,58.536798,27.557843,...,59.446463,26.456785,3.539500,96.971297,26.401863,3.152274,86.694989,28.210375,29.512916,27.728735
std,5.119721,318.224739,102.628337,19.622634,1.306621,85.177784,4.116195,1.728860,51.344133,2.095805,...,53.840742,3.422042,2.647375,72.682837,3.681483,2.324980,64.422343,7.422163,9.502396,8.988269
min,4.200001,0.876493,1.591053,0.500673,0.000000,0.000000,11.205263,0.000000,0.000000,11.237787,...,0.000000,11.858594,0.000000,0.000000,13.312500,0.000000,0.000000,4.810156,4.100000,3.100000
25%,16.000000,146.076505,57.101142,9.524865,1.616667,137.509050,26.550000,0.622500,14.210875,26.950000,...,13.515000,26.800000,0.982500,24.276000,26.750000,1.042500,25.032594,22.500000,21.700000,20.600000
50%,20.166666,406.791180,94.517320,23.863689,2.500000,226.826260,28.050000,1.625000,45.135000,27.850000,...,44.444000,27.400000,3.205000,90.747062,27.500000,2.810000,80.063125,28.900000,29.500000,27.500000
75%,23.800002,707.318620,156.228685,42.676916,3.416667,271.970655,29.250000,3.150000,91.253344,28.850000,...,92.767500,28.100000,6.097500,167.408438,28.350000,5.105000,142.698625,33.800000,37.100000,34.900000
max,35.399996,1438.887200,776.552080,81.365264,9.833334,359.998440,36.800000,8.095000,228.279000,36.900000,...,244.876500,36.550000,10.237500,303.030000,36.000000,10.237500,297.399375,55.100000,56.900000,105.800000

### Working with data from 2015

In [148]:
data_meteo_15 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2015.csv',
                            sep=';')
data_pv_15 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2015.csv',
                         sep=';')

In [149]:
data_meteo_15.shape

(437159, 9)

In [150]:
data_pv_15.shape

(242735, 25)

In [151]:
data_meteo_15 = data_meteo_15.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [152]:
data_pv_15 = data_pv_15.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [153]:
data_meteo_15['Datetime'] = pd.to_datetime(data_meteo_15['Datetime'], utc=True)
data_pv_15['Datetime'] = pd.to_datetime(data_pv_15['Datetime'], utc=True)

In [154]:
# Sortting by date

data_meteo_15 = data_meteo_15.sort_values('Datetime').reset_index(drop=True)
data_pv_15 = data_pv_15.sort_values('Datetime').reset_index(drop=True)

In [155]:
final_dataset_15 = pd.merge (left = data_meteo_15, right = data_pv_15, left_on = 'Datetime', right_on = 'Datetime')

In [156]:
final_dataset_15.shape

(225510, 33)

In [157]:
final_dataset_15.drop(['Datetime', 'Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [158]:
final_dataset_15 = fill_gap (final_dataset_15, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [159]:
final_dataset_15.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,...,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000,225499.000000
mean,21.135466,462.059383,127.921139,27.785569,2.586359,196.572236,26.066274,2.060262,58.080369,27.322064,...,58.567904,26.166733,3.629897,99.033002,26.247499,3.210207,88.318760,29.068731,30.657794,28.858024
std,5.432284,319.843669,103.215874,19.355916,1.306946,85.386276,4.587664,1.702535,50.826816,2.269292,...,52.986153,3.729086,2.689057,73.652859,4.005837,2.310003,64.180791,7.514115,9.771258,9.185867
min,3.166667,1.337505,1.606723,0.557327,0.000000,0.000000,12.350000,0.000000,0.000000,10.910491,...,0.000000,12.000000,0.000000,0.000000,11.700000,0.000000,0.000000,3.515234,2.300000,1.600000
25%,17.250000,161.759810,60.120680,10.066195,1.616667,125.674250,26.400000,0.637500,13.953750,26.900000,...,13.112000,26.700000,1.005000,24.593125,26.750000,1.067500,25.574813,23.600000,22.800000,21.700000
50%,21.199998,442.888080,99.838872,25.360398,2.516667,215.830100,27.850000,1.630000,44.797500,27.650000,...,43.625000,27.300000,3.340000,94.116750,27.500000,2.967500,84.736750,30.000000,31.000000,29.100000
75%,25.000000,742.343720,159.232030,44.226692,3.416667,261.980850,29.150000,3.105000,90.117000,28.650000,...,90.884625,27.950000,6.290000,171.675000,28.350000,5.202500,146.001250,34.900000,38.700000,36.100000
max,37.166668,1421.328200,720.352560,84.266016,9.700002,359.999160,34.400000,7.997500,236.664000,34.650000,...,243.975000,34.900000,10.237500,302.006250,34.450000,10.237500,300.982500,48.400000,55.500000,53.300000

### Working with data from 2016

In [160]:
data_meteo_16 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2016.csv',
                            sep=';')
data_pv_16 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2016.csv',
                         sep=';')

In [161]:
data_meteo_16.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Direct Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2016-03-22T07:58:00+00:00,11.083334,307.19950,144.84512,12.533846,3.133333,300.66464,NaN,NaN
1,2016-03-22T08:00:00+00:00,11.100000,174.47252,150.80226,10.975560,2.900000,294.33660,NaN,NaN
2,2016-03-22T08:02:00+00:00,11.166666,360.01548,143.93522,14.223366,3.766667,300.83378,NaN,NaN
3,2016-03-22T08:06:00+00:00,11.233334,375.56660,128.84222,15.575274,2.683334,299.33326,NaN,NaN
4,2016-03-22T08:08:00+00:00,11.300000,376.88700,120.42222,15.897234,3.433333,295.83228,NaN,NaN

In [162]:
data_pv_16.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2016-02-11T15:34:00+00:00,28.50,1.1275,32.13375,29.40,1.5725,46.231500,27.10,1.4625,39.63375,...,31.050000,27.55,1.5675,43.184625,27.25,1.4125,38.490625,24.5,22.8,22.5
1,2016-06-10T13:23:00+00:00,29.50,1.7725,52.28875,34.20,0.8050,27.531000,28.50,4.2500,121.12500,...,51.051000,28.15,3.8550,108.518250,28.10,4.1750,117.317500,37.0,42.3,43.5
2,2016-02-11T10:41:00+00:00,30.20,1.4775,44.62050,29.25,2.4250,70.931250,29.25,2.2850,66.83625,...,44.846875,28.70,2.3825,68.377750,28.95,2.2275,64.486125,27.4,25.7,24.9
3,2016-06-10T13:25:00+00:00,29.50,1.9775,58.33625,34.45,0.8100,27.904500,28.30,5.0950,144.18850,...,56.889875,27.70,4.6775,129.566750,28.35,4.9400,140.049000,37.2,43.3,44.4
4,2016-02-11T10:44:00+00:00,29.75,1.4450,42.98875,29.25,2.2375,65.446875,30.15,1.9200,57.88800,...,42.333000,28.30,2.2000,62.260000,28.70,1.9550,56.108500,27.1,25.3,24.6

In [163]:
data_meteo_16.shape

(399744, 9)

In [164]:
data_pv_16.shape

(177772, 25)

In [165]:
data_meteo_16.columns

Index(['Datetime', 'Ambient Temperature [ºC]', 'Global Radiation [W/m2]',
       'Direct Radiation [W/m2]', 'Ultraviolet [W/m2]', 'Wind Velocity [m/s]',
       'Wind Direction [º]', 'Precipitation [mm]',
       'Atmospheric pressure [hPa]'],
      dtype='object')

In [166]:
data_meteo_16 = data_meteo_16.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Direct Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [167]:
data_pv_16 = data_pv_16.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [168]:
data_meteo_16['Datetime'] = pd.to_datetime(data_meteo_16['Datetime'], utc=True)
data_pv_16['Datetime'] = pd.to_datetime(data_pv_16['Datetime'], utc=True)

In [169]:
# Sortting by date

data_meteo_16 = data_meteo_16.sort_values('Datetime').reset_index(drop=True)
data_pv_16 = data_pv_16.sort_values('Datetime').reset_index(drop=True)

In [170]:
final_dataset_16 = pd.merge (left = data_meteo_16, right = data_pv_16, left_on = 'Datetime', right_on = 'Datetime')

In [171]:
final_dataset_16.shape

(139080, 33)

In [172]:
final_dataset_16.drop(['Datetime', 'Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [173]:
final_dataset_16 = fill_gap (final_dataset_16, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [174]:
final_dataset_16.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,...,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000,139057.000000
mean,21.915041,437.300385,113.209025,26.515064,2.614318,191.581453,25.885418,2.085426,58.616335,27.585566,...,59.107307,26.159812,3.472106,94.541032,26.008123,3.039815,82.649881,29.957944,31.027824,29.173581
std,6.347771,315.737441,88.084871,19.561412,1.344107,90.957627,4.698047,1.791377,53.489842,3.095270,...,55.919735,3.664857,2.591010,70.833879,3.970745,2.261582,61.826733,7.941895,10.253741,10.041414
min,4.600000,1.418935,1.745721,0.558989,0.000000,0.000000,12.400000,0.000000,0.000000,10.298824,...,0.000000,13.110000,0.000000,0.000000,12.325000,0.000000,0.000000,4.527734,3.900000,2.800000
25%,16.500000,146.692500,55.736652,9.307752,1.633333,112.820280,26.250000,0.615000,13.333125,27.200000,...,12.682500,26.550000,0.927500,22.685625,26.550000,0.982500,23.312625,23.600000,22.400000,20.900000
50%,22.383334,401.623160,88.939464,22.673622,2.500000,200.162740,27.600000,1.605000,43.436250,28.150000,...,42.154500,27.250000,3.192500,90.045000,27.100000,2.690000,76.557500,31.100000,30.700000,27.700000
75%,27.433334,701.407920,145.257260,41.829000,3.450000,269.338260,28.950000,3.075000,88.497250,29.450000,...,88.740000,27.950000,6.015000,163.671000,28.150000,4.922500,136.062375,36.300000,39.800000,38.300000
max,38.300000,1413.023400,714.390160,83.990568,12.283334,359.997880,35.050000,8.105000,245.176250,35.300000,...,255.985500,35.150000,10.237500,298.423125,35.100000,10.235000,288.023250,51.100000,62.000000,62.100000

### Working with data from 2017

In [175]:
data_meteo_17 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-meteo-2017.csv',
                            sep=';')
data_pv_17 = pd.read_csv('/home/dsc/Documents/TFM-Sun-Power-Prediction/dataset/sunlab-faro-pv-2017.csv',
                         sep=';')

In [176]:
data_meteo_17.head()

,Datetime,Ambient Temperature [ºC],Global Radiation [W/m2],Diffuse Radiation [W/m2],Ultraviolet [W/m2],Wind Velocity [m/s],Wind Direction [º],Precipitation [mm],Atmospheric pressure [hPa]
0,2017-06-13T04:11:00+02:00,21.4,1.135318,1.688030,0.508061,4.150000,105.84458,0.0,1007.0334
1,2017-06-13T04:12:00+02:00,21.4,1.202852,1.693716,0.508069,2.850000,104.66702,0.0,1007.0334
2,2017-06-13T04:16:00+02:00,21.5,1.311066,1.710920,0.509157,3.683334,103.33748,0.0,1007.0668
3,2017-06-13T04:34:00+02:00,21.6,1.530087,1.683353,0.503610,3.433334,113.17200,0.0,1007.1334
4,2017-06-23T23:29:00+02:00,29.0,1.901296,2.147049,0.508236,0.566667,247.80524,0.0,1018.3000

In [177]:
data_pv_17.head()

,Datetime,A_Vertical - Voltage DC [V],A_Vertical - Current DC [A],A_Vertical - Power DC [W],A_Optimal - Voltage DC [V],A_Optimal - Current DC [A],A_Optimal - Power DC [W],A_Horizontal - Voltage DC [V],A_Horizontal - Current DC [A],A_Horizontal - Power DC [W],...,B_Vertical - Power DC [W],B_Optimal - Voltage DC [V],B_Optimal - Current DC [A],B_Optimal - Power DC [W],B_Horizontal - Voltage DC [V],B_Horizontal - Current DC [A],B_Horizontal - Power DC [W],B_Vertical - Temperature [ºC],B_Optimal - Temperature [ºC],B_Horizontal - Temperature [ºC]
0,2017-04-12T17:28:00+00:00,27.00,0.8050,21.735000,28.35,1.6850,47.769750,28.05,1.8500,51.892500,...,20.709000,27.55,1.6325,44.975375,27.35,1.8225,49.845375,30.8,34.9,33.0
1,2017-04-12T17:34:00+00:00,26.65,0.7450,19.854250,27.90,1.5150,42.268500,27.75,1.6900,46.897500,...,19.193125,27.35,1.4575,39.862625,27.25,1.6650,45.371250,30.4,34.1,32.9
2,2017-04-12T17:43:00+00:00,26.95,0.6575,17.719625,27.55,1.2425,34.230875,27.60,1.4375,39.675000,...,16.919375,27.30,1.1850,32.350500,27.60,1.4050,38.778000,30.5,34.1,32.8
3,2017-04-12T17:47:00+00:00,27.05,0.6200,16.771000,27.55,1.1150,30.718250,27.65,1.3100,36.221500,...,15.849375,27.30,1.0600,28.938000,28.85,0.9075,26.181375,30.5,33.9,32.3
4,2017-04-12T17:57:00+00:00,26.95,0.5200,14.014000,27.40,0.8200,22.468000,28.75,0.9725,27.959375,...,13.174375,27.65,0.7675,21.221375,27.15,0.9950,27.014250,30.0,33.0,30.6

In [178]:
data_meteo_17['Datetime'] = pd.to_datetime(data_meteo_17['Datetime'], utc=True)
data_pv_17['Datetime'] = pd.to_datetime(data_pv_17['Datetime'], utc=True)

In [179]:
data_meteo_17 = data_meteo_17.rename(columns={'Ambient Temperature [ºC]':'Ambient_Temperature', 
                                              'Global Radiation [W/m2]':'Global_Radiation',
                                              'Diffuse Radiation [W/m2]':'Diffuse_Radiation', 
                                              'Ultraviolet [W/m2]':'Ultraviolet',
                                              'Wind Velocity [m/s]':'Wind_Velocity',
                                              'Wind Direction [º]':'Wind_direction', 
                                              'Precipitation [mm]':'Precipitation',
                                              'Atmospheric pressure [hPa]':'Atmospheric_pressure'})

In [180]:
data_pv_17 = data_pv_17.rename(columns={'A_Vertical - Voltage DC [V]':'A_Vertical_VDC',
                                              'A_Vertical - Current DC [A]':'A_Vertical_CDC', 
                                              'A_Vertical - Power DC [W]':'A_Vertical_PDC',
                                              'A_Optimal - Voltage DC [V]':'A_Optimal_VDC', 
                                              'A_Optimal - Current DC [A]':'A_Optimal_CDC',
                                              'A_Optimal - Power DC [W]':'A_Optimal_PDC', 
                                              'A_Horizontal - Voltage DC [V]':'A_Horizontal_VDC',
                                              'A_Horizontal - Current DC [A]':'A_Horizontal_CDC', 
                                              'A_Horizontal - Power DC [W]':'A_Horizontal_PDC',
                                              'A_Vertical - Temperature [ºC]':'A_Vertical_Temperature', 
                                              'A_Optimal - Temperature [ºC]':'A_Optimal_Temperature',
                                              'A_Horizontal - Temperature [ºC]':'A_Horizontal_Temperature', 
                                              'B_Vertical - Voltage DC [V]':'B_Vertical_VDC',
                                              'B_Vertical - Current DC [A]':'B_Vertical_CDC', 
                                              'B_Vertical - Power DC [W]':'B_Vertical_PDC',
                                              'B_Optimal - Voltage DC [V]':'B_Optimal_VDC', 
                                              'B_Optimal - Current DC [A]':'B_Optimal_CDC',
                                              'B_Optimal - Power DC [W]':'B_Optimal_PDC', 
                                              'B_Horizontal - Voltage DC [V]':'B_Horizontal_VDC',
                                              'B_Horizontal - Current DC [A]':'B_Horizontal_CDC', 
                                              'B_Horizontal - Power DC [W]':'B_Horizontal_PDC',
                                              'B_Vertical - Temperature [ºC]':'B_Vertical_Temperature', 
                                              'B_Optimal - Temperature [ºC]':'B_Optimal_Temperature',
                                              'B_Horizontal - Temperature [ºC]':'B_Horizontal_Temperature'})

In [181]:
data_meteo_17.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,Precipitation,Atmospheric_pressure
0,2017-06-13 02:11:00+00:00,21.4,1.135318,1.688030,0.508061,4.150000,105.84458,0.0,1007.0334
1,2017-06-13 02:12:00+00:00,21.4,1.202852,1.693716,0.508069,2.850000,104.66702,0.0,1007.0334
2,2017-06-13 02:16:00+00:00,21.5,1.311066,1.710920,0.509157,3.683334,103.33748,0.0,1007.0668
3,2017-06-13 02:34:00+00:00,21.6,1.530087,1.683353,0.503610,3.433334,113.17200,0.0,1007.1334
4,2017-06-23 21:29:00+00:00,29.0,1.901296,2.147049,0.508236,0.566667,247.80524,0.0,1018.3000

In [182]:
data_pv_17.head()

,Datetime,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,A_Optimal_CDC,A_Optimal_PDC,A_Horizontal_VDC,A_Horizontal_CDC,A_Horizontal_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2017-04-12 17:28:00+00:00,27.00,0.8050,21.735000,28.35,1.6850,47.769750,28.05,1.8500,51.892500,...,20.709000,27.55,1.6325,44.975375,27.35,1.8225,49.845375,30.8,34.9,33.0
1,2017-04-12 17:34:00+00:00,26.65,0.7450,19.854250,27.90,1.5150,42.268500,27.75,1.6900,46.897500,...,19.193125,27.35,1.4575,39.862625,27.25,1.6650,45.371250,30.4,34.1,32.9
2,2017-04-12 17:43:00+00:00,26.95,0.6575,17.719625,27.55,1.2425,34.230875,27.60,1.4375,39.675000,...,16.919375,27.30,1.1850,32.350500,27.60,1.4050,38.778000,30.5,34.1,32.8
3,2017-04-12 17:47:00+00:00,27.05,0.6200,16.771000,27.55,1.1150,30.718250,27.65,1.3100,36.221500,...,15.849375,27.30,1.0600,28.938000,28.85,0.9075,26.181375,30.5,33.9,32.3
4,2017-04-12 17:57:00+00:00,26.95,0.5200,14.014000,27.40,0.8200,22.468000,28.75,0.9725,27.959375,...,13.174375,27.65,0.7675,21.221375,27.15,0.9950,27.014250,30.0,33.0,30.6

In [183]:
final_dataset_17 = pd.merge (left = data_meteo_17, right = data_pv_17, left_on = 'Datetime', right_on = 'Datetime')

In [184]:
# Sortting by date

data_meteo_17 = data_meteo_17.sort_values('Datetime').reset_index(drop=True)
data_pv_17 = data_pv_17.sort_values('Datetime').reset_index(drop=True)

In [185]:
final_dataset_17.shape

(206957, 33)

In [186]:
final_dataset_17.drop(['Precipitation', 'Atmospheric_pressure'], axis='columns', inplace=True)

In [187]:
final_dataset_17.shape

(206957, 31)

In [188]:
final_dataset_17 = fill_gap (final_dataset_17, ['Ambient_Temperature', 'Global_Radiation',
       'Diffuse_Radiation', 'Ultraviolet', 'Wind_Velocity',
       'A_Vertical_VDC', 'A_Vertical_CDC', 'A_Vertical_PDC', 'A_Optimal_VDC',
       'A_Optimal_CDC', 'A_Optimal_PDC', 'A_Horizontal_VDC',
       'A_Horizontal_CDC', 'A_Horizontal_PDC', 'A_Vertical_Temperature',
       'A_Optimal_Temperature', 'A_Horizontal_Temperature', 'B_Vertical_VDC',
       'B_Vertical_CDC', 'B_Vertical_PDC', 'B_Optimal_VDC', 'B_Optimal_CDC',
       'B_Optimal_PDC', 'B_Horizontal_VDC', 'B_Horizontal_CDC',
       'B_Horizontal_PDC', 'B_Vertical_Temperature', 'B_Optimal_Temperature',
       'B_Horizontal_Temperature'])

In [189]:
final_dataset_17.shape

(203097, 31)

In [190]:
final_dataset_17.describe()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
count,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,...,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000,203097.000000
mean,21.399671,462.741953,129.134046,27.797956,2.651215,191.044225,26.305041,2.179694,61.484313,27.877210,...,61.673561,26.699803,3.690305,100.694488,26.394063,3.284258,89.842888,29.541031,30.813325,28.858751
std,5.586697,323.184808,104.771711,19.711869,1.261512,86.131858,4.500542,1.734413,51.597572,2.078557,...,53.777465,2.803538,2.614220,71.451994,3.582354,2.310777,63.677210,7.820928,9.866402,9.366542
min,3.000000,0.732156,1.626869,0.501036,0.000000,0.000000,12.450000,0.000000,0.000000,14.434277,...,0.000000,14.345508,0.000000,0.000000,14.337500,0.000000,0.000000,4.609375,3.000000,2.100000
25%,17.000000,167.679020,60.578404,10.186330,1.750000,116.856400,26.650000,0.725000,16.317500,27.350000,...,15.168000,26.750000,1.140000,28.938000,26.750000,1.147500,28.093375,23.800000,22.900000,21.500000
50%,21.433334,447.357880,99.255776,25.675188,2.566667,202.842860,28.000000,1.790000,49.886125,28.100000,...,48.025000,27.350000,3.550000,99.928125,27.350000,3.072500,87.188000,30.500000,31.100000,29.000000
75%,25.933334,731.379680,174.083680,43.740232,3.416667,261.936860,29.250000,3.260000,94.696875,29.050000,...,95.215000,28.050000,6.237500,169.830000,28.200000,5.200000,143.592000,35.400000,38.800000,36.300000
max,37.899996,1484.379800,715.146720,85.515376,10.300000,359.999200,34.700000,7.985000,244.295250,35.200000,...,250.965000,34.850000,10.237500,310.708125,34.150000,10.237500,296.681875,49.300000,58.500000,54.500000

### Savings last week of 2017 to final test

In [191]:
#Savings last week of year
final_dataset_17[final_dataset_17['Datetime'] > '2017-12-24'].to_csv('test_dataset_17.csv', sep=';', index=False)

In [192]:
# Dropping last week of year
final_dataset_17 = final_dataset_17.drop(final_dataset_17[final_dataset_17['Datetime'] > '2017-12-24'].index)
final_dataset_17.reset_index()

,index,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,0,2017-06-13 06:03:00+00:00,21.600000,71.765680,69.939760,5.399191,3.300000,129.81660,14.90,0.1600,...,2.279875,15.1000,0.2400,3.612000,19.15,0.2425,4.643875,23.8,22.9,22.7
1,1,2017-06-13 06:05:00+00:00,21.600000,115.415920,112.862560,8.290771,4.283334,130.50446,14.90,0.1775,...,2.458500,15.0000,0.2750,4.152500,19.25,0.2950,5.678750,23.8,23.0,22.7
2,2,2017-06-13 06:20:00+00:00,21.816666,109.468120,109.427260,8.246832,2.500000,123.67884,14.60,0.3675,...,4.932000,14.9500,0.5350,7.971500,18.95,0.6100,11.559500,24.0,23.2,23.0
3,3,2017-06-13 06:21:00+00:00,21.900000,107.936160,107.846820,8.153960,3.150000,125.28878,14.55,0.3750,...,5.040000,14.9250,0.5325,7.934250,19.30,0.6075,11.724750,24.0,23.2,23.0
4,4,2017-06-13 06:23:00+00:00,21.850000,99.323296,97.557976,7.782180,4.033333,130.16754,14.55,0.4175,...,5.694000,15.0625,0.6525,9.722250,19.30,0.7650,14.764500,24.0,23.2,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198550,206951,2017-07-01 18:14:00+00:00,26.199998,65.107996,29.519826,4.319071,2.483333,295.95556,26.85,0.4925,...,11.836875,26.9500,0.5175,13.946625,26.85,1.5925,42.758625,31.2,32.2,32.9
198551,206952,2017-07-01 18:41:00+00:00,25.699998,18.520666,16.183050,1.759812,1.500000,307.33380,26.70,0.3950,...,8.610750,26.9000,0.2750,7.397500,27.00,0.9125,24.637500,31.8,30.6,32.0
198552,206953,2017-07-01 18:57:00+00:00,25.100000,7.485613,6.993582,0.873425,0.816667,320.97644,26.30,0.3200,...,6.823750,26.7500,0.2325,6.219375,27.00,0.5550,14.985000,33.1,30.2,31.9
198553,206954,2017-07-01 19:13:00+00:00,24.400000,3.709006,4.063614,0.557801,1.550000,311.33332,26.20,0.2175,...,4.808875,26.9000,0.1675,4.505750,26.80,0.2700,7.236000,31.7,29.2,30.8
198554,206955,2017-07-01 19:52:00+00:00,22.800002,2.253112,2.480813,0.511687,1.283333,317.17392,22.35,0.0325,...,0.538125,24.2000,0.0325,0.786500,24.50,0.0350,0.857500,30.5,28.3,29.2

In [193]:
final_dataset_17.head()

,Datetime,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,2017-06-13 06:03:00+00:00,21.600000,71.765680,69.939760,5.399191,3.300000,129.81660,14.90,0.1600,2.384000,...,2.279875,15.1000,0.2400,3.61200,19.15,0.2425,4.643875,23.8,22.9,22.7
1,2017-06-13 06:05:00+00:00,21.600000,115.415920,112.862560,8.290771,4.283334,130.50446,14.90,0.1775,2.644750,...,2.458500,15.0000,0.2750,4.15250,19.25,0.2950,5.678750,23.8,23.0,22.7
2,2017-06-13 06:20:00+00:00,21.816666,109.468120,109.427260,8.246832,2.500000,123.67884,14.60,0.3675,5.365500,...,4.932000,14.9500,0.5350,7.97150,18.95,0.6100,11.559500,24.0,23.2,23.0
3,2017-06-13 06:21:00+00:00,21.900000,107.936160,107.846820,8.153960,3.150000,125.28878,14.55,0.3750,5.456250,...,5.040000,14.9250,0.5325,7.93425,19.30,0.6075,11.724750,24.0,23.2,23.0
4,2017-06-13 06:23:00+00:00,21.850000,99.323296,97.557976,7.782180,4.033333,130.16754,14.55,0.4175,6.074625,...,5.694000,15.0625,0.6525,9.72225,19.30,0.7650,14.764500,24.0,23.2,23.0

In [194]:
# Dropping datetime columns.
final_dataset_17.drop(['Datetime'], axis='columns', inplace=True)

In [195]:
final_dataset_17.head()

,Ambient_Temperature,Global_Radiation,Diffuse_Radiation,Ultraviolet,Wind_Velocity,Wind_direction,A_Vertical_VDC,A_Vertical_CDC,A_Vertical_PDC,A_Optimal_VDC,...,B_Vertical_PDC,B_Optimal_VDC,B_Optimal_CDC,B_Optimal_PDC,B_Horizontal_VDC,B_Horizontal_CDC,B_Horizontal_PDC,B_Vertical_Temperature,B_Optimal_Temperature,B_Horizontal_Temperature
0,21.600000,71.765680,69.939760,5.399191,3.300000,129.81660,14.90,0.1600,2.384000,23.65,...,2.279875,15.1000,0.2400,3.61200,19.15,0.2425,4.643875,23.8,22.9,22.7
1,21.600000,115.415920,112.862560,8.290771,4.283334,130.50446,14.90,0.1775,2.644750,23.65,...,2.458500,15.0000,0.2750,4.15250,19.25,0.2950,5.678750,23.8,23.0,22.7
2,21.816666,109.468120,109.427260,8.246832,2.500000,123.67884,14.60,0.3675,5.365500,23.95,...,4.932000,14.9500,0.5350,7.97150,18.95,0.6100,11.559500,24.0,23.2,23.0
3,21.900000,107.936160,107.846820,8.153960,3.150000,125.28878,14.55,0.3750,5.456250,23.95,...,5.040000,14.9250,0.5325,7.93425,19.30,0.6075,11.724750,24.0,23.2,23.0
4,21.850000,99.323296,97.557976,7.782180,4.033333,130.16754,14.55,0.4175,6.074625,24.00,...,5.694000,15.0625,0.6525,9.72225,19.30,0.7650,14.764500,24.0,23.2,23.0

### Saving data train

In [196]:
final_train_dataset = pd.concat([final_dataset_14, final_dataset_15, 
                                 final_dataset_16, final_dataset_17], axis = 0).reset_index(drop = True)
final_train_dataset.to_csv('train_dataset.csv', sep=';', index=False)